/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fietsverhuur.swing;

import fietsverhuur.model.*;
import fietsverhuur.dao.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Myra
 */
public class FietsenSearchDialog extends javax.swing.JDialog {

    /**
     * Creates new form FietsenSearchDialog
     */
    private DefaultListModel<Fiets> fietsenmodel;
    
    public FietsenSearchDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fietsenmodel = new DefaultListModel<Fiets>();
        lstZoekresultaten.setModel(fietsenmodel);
    }
    public void showDialog() {
        this.setModal(true);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnCloseThisGUI = new javax.swing.JButton();
        lblFietsnummer = new javax.swing.JLabel();
        txtAantalVitessen = new javax.swing.JTextField();
        lblZoekresultatenList = new javax.swing.JLabel();
        btnSearchFietsen = new javax.swing.JButton();
        lblTitel = new javax.swing.JLabel();
        btnOpenFietsenEditDialog = new javax.swing.JButton();
        btnOpenFietsenDeleteDialog = new javax.swing.JButton();
        txtFietsnummer = new javax.swing.JTextField();
        lblKleur = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblFietstype = new javax.swing.JLabel();
        lblVerhuurpuntId = new javax.swing.JLabel();
        txtVerhuurpuntId = new javax.swing.JTextField();
        lblDikteBand = new javax.swing.JLabel();
        lblAantalVitessen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstZoekresultaten = new javax.swing.JList();
        txtKleur = new javax.swing.JTextField();
        cmbFietstype = new javax.swing.JComboBox();
        cmbGender = new javax.swing.JComboBox();
        cmbDikteBand = new javax.swing.JComboBox();
        btnOpenFietsenDetailsDialog = new javax.swing.JButton();
        lblFoutmelding = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCloseThisGUI.setText("Sluit venster");
        btnCloseThisGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseThisGUIActionPerformed(evt);
            }
        });

        lblFietsnummer.setText("Fietsnummer");

        txtAantalVitessen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAantalVitessenKeyReleased(evt);
            }
        });

        lblZoekresultatenList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblZoekresultatenList.setText("Resultaten:");

        btnSearchFietsen.setText("Zoek fiets");
        btnSearchFietsen.setEnabled(false);
        btnSearchFietsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFietsenActionPerformed(evt);
            }
        });

        lblTitel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTitel.setText("Zoek fietsen");
        lblTitel.setToolTipText("");

        btnOpenFietsenEditDialog.setText("Edit selectie");
        btnOpenFietsenEditDialog.setEnabled(false);
        btnOpenFietsenEditDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFietsenEditDialogActionPerformed(evt);
            }
        });

        btnOpenFietsenDeleteDialog.setText("Verwijder selectie");
        btnOpenFietsenDeleteDialog.setEnabled(false);
        btnOpenFietsenDeleteDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFietsenDeleteDialogActionPerformed(evt);
            }
        });

        txtFietsnummer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFietsnummerKeyReleased(evt);
            }
        });

        lblKleur.setText("Kleur");

        lblGender.setText("Gender");

        lblFietstype.setText("Fietstype");

        lblVerhuurpuntId.setText("VerhuurpuntId");

        txtVerhuurpuntId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVerhuurpuntIdKeyReleased(evt);
            }
        });

        lblDikteBand.setText("Dikte band");

        lblAantalVitessen.setText("Aantal Vitessen");

        lstZoekresultaten.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstZoekresultatenValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstZoekresultaten);

        txtKleur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKleurKeyReleased(evt);
            }
        });

        cmbFietstype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kies type...", "stadsfiets", "sportfiets" }));
        cmbFietstype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFietstypeItemStateChanged(evt);
            }
        });

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kies gender...", "mannelijk", "vrouwelijk", "unisex" }));
        cmbGender.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbGenderItemStateChanged(evt);
            }
        });

        cmbDikteBand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kies dikte...", "dun", "middel", "dik" }));
        cmbDikteBand.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDikteBandItemStateChanged(evt);
            }
        });

        btnOpenFietsenDetailsDialog.setText("Details selectie");
        btnOpenFietsenDetailsDialog.setEnabled(false);
        btnOpenFietsenDetailsDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFietsenDetailsDialogActionPerformed(evt);
            }
        });

        lblFoutmelding.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCloseThisGUI)
                            .addComponent(lblZoekresultatenList)
                            .addComponent(lblTitel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFietsnummer, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(lblFietsnummer)
                                    .addComponent(lblAantalVitessen)
                                    .addComponent(txtAantalVitessen, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(btnSearchFietsen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDikteBand)
                                            .addComponent(cmbDikteBand, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblKleur)
                                            .addComponent(txtKleur, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblGender, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbGender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblFietstype)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(cmbFietstype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblVerhuurpuntId)
                                            .addComponent(txtVerhuurpuntId, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1)))))
                        .addGap(117, 117, 117))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOpenFietsenDeleteDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenFietsenEditDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenFietsenDetailsDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFoutmelding)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFietsnummer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFietsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAantalVitessen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAantalVitessen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFietstype)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbFietstype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVerhuurpuntId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVerhuurpuntId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDikteBand)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtKleur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbDikteBand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblKleur)
                                .addGap(26, 26, 26)))))
                .addGap(26, 26, 26)
                .addComponent(btnSearchFietsen)
                .addGap(18, 18, 18)
                .addComponent(lblFoutmelding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(lblZoekresultatenList, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpenFietsenEditDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenFietsenDetailsDialog)
                        .addGap(11, 11, 11)
                        .addComponent(btnOpenFietsenDeleteDialog)))
                .addGap(18, 18, 18)
                .addComponent(btnCloseThisGUI)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFietsnummerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFietsnummerKeyReleased
        if(checkIfEmpty(txtFietsnummer)) {
            btnSearchFietsen.setEnabled(false);
        } else {
            if(CheckUserInput.isStringInteger(txtFietsnummer.getText())) {
                btnSearchFietsen.setEnabled(true);
                lblFoutmelding.setText("");
            } else {
                btnSearchFietsen.setEnabled(false);
                lblFoutmelding.setText("Vul a.u.b. een geldig nummer in.");
            }
        }
    }//GEN-LAST:event_txtFietsnummerKeyReleased

    private void cmbGenderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbGenderItemStateChanged
        if(checkIfValueSelected(cmbGender)) {
            btnSearchFietsen.setEnabled(false);
        } else {
            btnSearchFietsen.setEnabled(true);
        }
    }//GEN-LAST:event_cmbGenderItemStateChanged

    private void cmbFietstypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFietstypeItemStateChanged
        if(checkIfValueSelected(cmbFietstype)) {
            btnSearchFietsen.setEnabled(false);
        } else {
            btnSearchFietsen.setEnabled(true);
        }
    }//GEN-LAST:event_cmbFietstypeItemStateChanged

    private void txtVerhuurpuntIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVerhuurpuntIdKeyReleased
        if(checkIfEmpty(txtVerhuurpuntId)) {
            btnSearchFietsen.setEnabled(false);
        } else {
            if(CheckUserInput.doesVerhuurpuntIdExist(txtVerhuurpuntId.getText(), lblFoutmelding)) {
                btnSearchFietsen.setEnabled(true);
            } else {
                btnSearchFietsen.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtVerhuurpuntIdKeyReleased

    private void txtAantalVitessenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAantalVitessenKeyReleased
        if(checkIfEmpty(txtAantalVitessen)) {
            btnSearchFietsen.setEnabled(false);
        } else {
            if(CheckUserInput.isStringInteger(txtAantalVitessen.getText())) {
                btnSearchFietsen.setEnabled(true);
                lblFoutmelding.setText("");
            } else {
                btnSearchFietsen.setEnabled(false);
                lblFoutmelding.setText("Vul a.u.b. een geldig aantal vitessen in.");
            }
        }
    }//GEN-LAST:event_txtAantalVitessenKeyReleased

    private void cmbDikteBandItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDikteBandItemStateChanged
        if(checkIfValueSelected(cmbDikteBand)) {
            btnSearchFietsen.setEnabled(false);
        } else {
            btnSearchFietsen.setEnabled(true);
        }
    }//GEN-LAST:event_cmbDikteBandItemStateChanged

    private void txtKleurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKleurKeyReleased
        if(checkIfEmpty(txtKleur)) {
            btnSearchFietsen.setEnabled(false);
        } else {
            btnSearchFietsen.setEnabled(true);
        }
    }//GEN-LAST:event_txtKleurKeyReleased

    private void btnSearchFietsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFietsenActionPerformed
        fietsenmodel.clear();
        if(txtFietsnummer.isEnabled()) {
            int fietsnummer = Integer.parseInt(txtFietsnummer.getText());
            Fiets gevondenFiets = FietsDao.getFietsById(fietsnummer);
            fietsenmodel.addElement(gevondenFiets);
        }
        if(cmbGender.isEnabled()) {
            String gender = cmbGender.getModel().getSelectedItem().toString();
            ArrayList<Fiets> gevondenFietsenLijst = FietsDao.getFietsenByGender(gender);
            for(Fiets gevondenFiets : gevondenFietsenLijst) {
                fietsenmodel.addElement(gevondenFiets);
            }
        }
        if(cmbFietstype.isEnabled()) {
            String fietstype = cmbFietstype.getModel().getSelectedItem().toString();
            ArrayList<Fiets> gevondenFietsenLijst = FietsDao.getFietsenByFietstype(fietstype);
            for(Fiets gevondenFiets : gevondenFietsenLijst) {
                fietsenmodel.addElement(gevondenFiets);
            }
        }
        if(txtVerhuurpuntId.isEnabled()) {
            int verhuurpuntId = Integer.parseInt(txtVerhuurpuntId.getText());
            ArrayList<Fiets> gevondenFietsenLijst = FietsDao.getFietsenByVerhuurpuntId(verhuurpuntId);
            for(Fiets gevondenFiets : gevondenFietsenLijst) {
                fietsenmodel.addElement(gevondenFiets);
            }
        }
        if(txtAantalVitessen.isEnabled()) {
            int aantalVitessen = Integer.parseInt(txtAantalVitessen.getText());
            ArrayList<Fiets> gevondenFietsenLijst = FietsDao.getFietsenByAantalVitessen(aantalVitessen);
            for(Fiets gevondenFiets : gevondenFietsenLijst) {
                fietsenmodel.addElement(gevondenFiets);
            }
        }
        if(cmbDikteBand.isEnabled()) {
            String dikteBand = cmbDikteBand.getModel().getSelectedItem().toString();
            ArrayList<Fiets> gevondenFietsenLijst = FietsDao.getFietsenByDikteBand(dikteBand);
            for(Fiets gevondenFiets : gevondenFietsenLijst) {
                fietsenmodel.addElement(gevondenFiets);
            }
        }
        if(txtKleur.isEnabled()) {
            String kleur = txtKleur.getText();
            ArrayList<Fiets> gevondenFietsenLijst = FietsDao.searchFietsenByKleur(kleur);
            for(Fiets gevondenFiets : gevondenFietsenLijst) {
                fietsenmodel.addElement(gevondenFiets);
            }
        }
    }//GEN-LAST:event_btnSearchFietsenActionPerformed

    private void lstZoekresultatenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstZoekresultatenValueChanged
        if (lstZoekresultaten.isSelectionEmpty()) {
            btnOpenFietsenDeleteDialog.setEnabled(false);
            btnOpenFietsenEditDialog.setEnabled(false);
            btnOpenFietsenDetailsDialog.setEnabled(false);
        } else {
            btnOpenFietsenDeleteDialog.setEnabled(true);
            btnOpenFietsenEditDialog.setEnabled(true);
            btnOpenFietsenDetailsDialog.setEnabled(true);
        }
    }//GEN-LAST:event_lstZoekresultatenValueChanged

    private void btnOpenFietsenEditDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFietsenEditDialogActionPerformed
        ArrayList <Fiets> fietsenToEdit = new ArrayList <Fiets> (lstZoekresultaten.getSelectedValuesList());
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        FietsenEditDialog dialog = new FietsenEditDialog(frame, true);
        dialog.createTextFieldsAndSetFietsen(fietsenToEdit);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        if(dialog.showDialog() == FietsenEditDialog.Resultaat.BEVESTIGD) {
            ArrayList<Fiets> gewijzigdeFietsen = dialog.getFietsen();
            for(Fiets gewijzigdeFiets : gewijzigdeFietsen){
                FietsDao.updateFiets(gewijzigdeFiets);
            }
        }
        btnSearchFietsenActionPerformed(evt);
    }//GEN-LAST:event_btnOpenFietsenEditDialogActionPerformed

    private void btnOpenFietsenDetailsDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFietsenDetailsDialogActionPerformed
        ArrayList <Fiets> fietsenToShow = new ArrayList <Fiets> (lstZoekresultaten.getSelectedValuesList());
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        FietsenDetailsDialog dialog = new FietsenDetailsDialog(frame, true);
        dialog.createTextFieldsAndSetFietsen(fietsenToShow);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
    }//GEN-LAST:event_btnOpenFietsenDetailsDialogActionPerformed

    private void btnOpenFietsenDeleteDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFietsenDeleteDialogActionPerformed
        ArrayList <Fiets> fietsenToDelete = new ArrayList <Fiets> (lstZoekresultaten.getSelectedValuesList());
        
        
        ArrayList <Verhuring> existingVerhuringen = new ArrayList <Verhuring>();
        ArrayList <Herstelling> existingHerstellingen = new ArrayList <Herstelling>();
        for(Fiets fiets : fietsenToDelete) {
            for(Verhuring verhuring : VerhuringDao.getVerhuringenByFietsnummer(fiets.getFietsnummer())) {
                existingVerhuringen.add(verhuring);
            }
            for(Herstelling herstelling : HerstellingDao.getHerstellingenByFietsnummer(fiets.getFietsnummer())) {
                existingHerstellingen.add(herstelling);
            }
        }
        
        if(existingVerhuringen.size() > 0 || existingHerstellingen.size() > 0) {
            String message = "Onderstaande verhuringen en/of herstellingen zijn teruggevonden op de door u geselecteerde fietsen:\n\n";
            for(Verhuring verhuring: existingVerhuringen) {
                message += "Verhuring " + Integer.toString(verhuring.getVerhuringId()) + ": fiets " + Integer.toString(verhuring.getFietsnummer()) + ".\n";
            }
            for(Herstelling herstelling: existingHerstellingen) {
                message += "Herstelling " + Integer.toString(herstelling.getHerstellingId()) + ": fiets " + Integer.toString(herstelling.getFietsnummer()) + ".\n";
            }
            message += "\nU kunt de geselecteerde fietsen pas verwijderen, wanneer deze verhuringen en/of herstellingen verwijderd zijn.\nWenst u deze eerst te verwijderen?";
            Object[] options = {"Nee, verwijder niets.", "Ja, verwijder de verhuringen/herstellingen"};
            int choice = JOptionPane.showOptionDialog(this,
                                                      message,
                                                      "Verhuringen/herstellingen teruggevonden",
                                                      JOptionPane.YES_NO_OPTION,
                                                      JOptionPane.INFORMATION_MESSAGE,
                                                      null,
                                                      options,
                                                      options[0]);
            if (choice == 1) {
                for(Verhuring verhuring: existingVerhuringen) {
                    VerhuringDao.verwijderVerhuring(verhuring.getVerhuringId());
                }
                for(Herstelling herstelling: existingHerstellingen) {
                    DeelherstellingDao.verwijderDeelherstellingenByHerstellingId(herstelling.getHerstellingId());
                    HerstellingDao.verwijderHerstelling(herstelling.getHerstellingId());
                }
                
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                FietsenDeleteDialog dialog = new FietsenDeleteDialog(frame, true);
                dialog.createTextFieldsAndSetFietsen(fietsenToDelete);
                dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
                if(dialog.showDialog() == FietsenDeleteDialog.Resultaat.BEVESTIGD) {
                    for(Fiets fietsToDelete : fietsenToDelete) {
                        FietsDao.verwijderFiets(fietsToDelete.getFietsnummer());
                    }
                }
                btnSearchFietsenActionPerformed(evt);
            }
        } else {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            FietsenDeleteDialog dialog = new FietsenDeleteDialog(frame, true);
            dialog.createTextFieldsAndSetFietsen(fietsenToDelete);
            dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
            if(dialog.showDialog() == FietsenDeleteDialog.Resultaat.BEVESTIGD) {
                for(Fiets fietsToDelete : fietsenToDelete) {
                    FietsDao.verwijderFiets(fietsToDelete.getFietsnummer());
                }
            }
            btnSearchFietsenActionPerformed(evt);
        }
        
    }//GEN-LAST:event_btnOpenFietsenDeleteDialogActionPerformed

    private void btnCloseThisGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseThisGUIActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseThisGUIActionPerformed

    public void setAllOtherComponents(boolean status, javax.swing.JComponent component) {
        ArrayList <javax.swing.JComponent> components = new ArrayList<>(9);
        components.add(txtFietsnummer);
        components.add(txtVerhuurpuntId);
        components.add(txtAantalVitessen);
        components.add(txtKleur);
        components.add(cmbGender);
        components.add(cmbFietstype);
        components.add(cmbDikteBand);
        for(javax.swing.JComponent currentcomponent : components) {
            if(currentcomponent != component) {
                currentcomponent.setEnabled(status);
            }
        }
    }
    public boolean checkIfEmpty(javax.swing.JTextField currenttextfield) {
        if(currenttextfield.getText().equals("")) {
            setAllOtherComponents(true, currenttextfield);
            lblFoutmelding.setText("");
            return true;
        } else {
            setAllOtherComponents(false, currenttextfield);
            return false;
        }
    }
    public boolean checkIfValueSelected(javax.swing.JComboBox currentcombobox) {
        if(currentcombobox.getModel().getSelectedItem().toString().contains("Kies")) {
            setAllOtherComponents(true, currentcombobox);
            lblFoutmelding.setText("");
            return true;
        } else {
            setAllOtherComponents(false, currentcombobox);
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FietsenSearchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FietsenSearchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FietsenSearchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FietsenSearchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FietsenSearchDialog dialog = new FietsenSearchDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseThisGUI;
    private javax.swing.JButton btnOpenFietsenDeleteDialog;
    private javax.swing.JButton btnOpenFietsenDetailsDialog;
    private javax.swing.JButton btnOpenFietsenEditDialog;
    private javax.swing.JButton btnSearchFietsen;
    private javax.swing.JComboBox cmbDikteBand;
    private javax.swing.JComboBox cmbFietstype;
    private javax.swing.JComboBox cmbGender;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAantalVitessen;
    private javax.swing.JLabel lblDikteBand;
    private javax.swing.JLabel lblFietsnummer;
    private javax.swing.JLabel lblFietstype;
    private javax.swing.JLabel lblFoutmelding;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblKleur;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblVerhuurpuntId;
    private javax.swing.JLabel lblZoekresultatenList;
    private javax.swing.JList lstZoekresultaten;
    private javax.swing.JTextField txtAantalVitessen;
    private javax.swing.JTextField txtFietsnummer;
    private javax.swing.JTextField txtKleur;
    private javax.swing.JTextField txtVerhuurpuntId;
    // End of variables declaration//GEN-END:variables
}
