/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fietsverhuur.swing;

import javax.swing.DefaultListModel;
import fietsverhuur.model.*;
import fietsverhuur.dao.*;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Myra
 */
public class fietsverhuurGUI extends javax.swing.JFrame {

    /**
     * Creates new form fietsverhuurGUI
     */
    private DefaultListModel<Verhuring> verhuringenModel;
    private DefaultListModel<Fiets> fietsenModel;
    private DefaultListModel<Huurder> huurdersModel;
    private DefaultListModel<Herstelling> herstellingenModel;
    
    public fietsverhuurGUI() {
        initComponents();
        pnlFietsen.setVisible(false);
        pnlHuurders.setVisible(false);
        pnlHerstellingen.setVisible(false);
        
        verhuringenModel = new DefaultListModel<Verhuring>();
        fietsenModel = new DefaultListModel<Fiets>();
        huurdersModel = new DefaultListModel<Huurder>();
        herstellingenModel = new DefaultListModel<Herstelling>();
        
        lstVerhuringen.setModel(verhuringenModel);
        lstFietsen.setModel(fietsenModel);
        lstHuurders.setModel(huurdersModel);
        lstHerstellingen.setModel(herstellingenModel);
        
        updateVerhuringenList();
        
        this.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width/2 - this.getWidth()/2, Toolkit.getDefaultToolkit().getScreenSize().height/2 - this.getHeight()/2);
    }

    public void updateVerhuringenList() {
        verhuringenModel.clear();
        ArrayList<Verhuring> verhuringenList = VerhuringDao.getVerhuringen();
        for (Verhuring huidigeVerhuring : verhuringenList) {
            verhuringenModel.addElement(huidigeVerhuring);
        }
    }
    public void updateFietsenList() {
        fietsenModel.clear();
        ArrayList<Fiets> fietsenList = FietsDao.getFietsen();
        for (Fiets huidigeFiets : fietsenList) {
            fietsenModel.addElement(huidigeFiets);
        }
    }
    public void updateHuurdersList() {
        huurdersModel.clear();
        ArrayList<Huurder> huurdersList = HuurderDao.getHuurders();
        for (Huurder huidigeHuurder : huurdersList) {
            huurdersModel.addElement(huidigeHuurder);
        }
    }
    public void updateHerstellingenList() {
        herstellingenModel.clear();
        ArrayList<Herstelling> herstellingenList = HerstellingDao.getHerstellingen();
        for (Herstelling huidigeHerstelling : herstellingenList) {
            herstellingenModel.addElement(huidigeHerstelling);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVerhuringen = new javax.swing.JPanel();
        lblVerhuringenList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstVerhuringen = new javax.swing.JList();
        btnOpenVerhuringenSearchDialog = new javax.swing.JButton();
        btnOpenVerhuringenEditDialog = new javax.swing.JButton();
        btnOpenVerhuringenDeleteDialog = new javax.swing.JButton();
        btnOpenVerhuringenCreateDialog = new javax.swing.JButton();
        btnFromVerhuringenToFietsen = new javax.swing.JButton();
        btnFromVerhuringenToHuurders = new javax.swing.JButton();
        btnFromVerhuringenToHerstellingen = new javax.swing.JButton();
        btnOpenVerhuringenDetailsDialog = new javax.swing.JButton();
        pnlFietsen = new javax.swing.JPanel();
        lblFietsenlist = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstFietsen = new javax.swing.JList();
        btnOpenFietsenSearchDialog = new javax.swing.JButton();
        btnOpenFietsenEditDialog = new javax.swing.JButton();
        btnOpenFietsenDeleteDialog = new javax.swing.JButton();
        btnOpenFietsenDetailsDialog = new javax.swing.JButton();
        btnOpenFietsenCreateDialog = new javax.swing.JButton();
        btnFromFietsenToVerhuringen = new javax.swing.JButton();
        btnFromFietsenToHerstellingen = new javax.swing.JButton();
        btnFromFietsenToHuurders = new javax.swing.JButton();
        pnlHuurders = new javax.swing.JPanel();
        lblHuurderList = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstHuurders = new javax.swing.JList();
        btnOpenHuurdersSearchDialog = new javax.swing.JButton();
        btnOpenHuurdersEditDialog = new javax.swing.JButton();
        btnOpenHuurdersDeleteDialog = new javax.swing.JButton();
        btnOpenHuurdersCreateDialog = new javax.swing.JButton();
        btnFromHuurdersToVerhuringen = new javax.swing.JButton();
        btnFromHuurdersToHerstellingen = new javax.swing.JButton();
        btnFromHuurdersToFietsen = new javax.swing.JButton();
        btnOpenHuurdersDetailsDialog = new javax.swing.JButton();
        pnlHerstellingen = new javax.swing.JPanel();
        btnHerstellingenList = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstHerstellingen = new javax.swing.JList();
        btnOpenHerstellingenSearchDialog = new javax.swing.JButton();
        btnOpenHerstellingenEditDialog = new javax.swing.JButton();
        btnOpenHerstellingenDeleteDialog = new javax.swing.JButton();
        btnOpenHerstellingenCreateDialog = new javax.swing.JButton();
        btnFromHerstellingenToVerhuringen = new javax.swing.JButton();
        btnFromHerstellingenToFietsen = new javax.swing.JButton();
        btnFromHerstellingentoHuurders = new javax.swing.JButton();
        btnOpenHerstellingenDetailsDialog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblVerhuringenList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblVerhuringenList.setText("Recente verhuringen");
        lblVerhuringenList.setToolTipText("");

        lstVerhuringen.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstVerhuringen.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstVerhuringenValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstVerhuringen);

        btnOpenVerhuringenSearchDialog.setText("Zoek verhuring");
        btnOpenVerhuringenSearchDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenVerhuringenSearchDialogActionPerformed(evt);
            }
        });

        btnOpenVerhuringenEditDialog.setText("Edit selectie");
        btnOpenVerhuringenEditDialog.setEnabled(false);
        btnOpenVerhuringenEditDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenVerhuringenEditDialogActionPerformed(evt);
            }
        });

        btnOpenVerhuringenDeleteDialog.setText("Verwijder selectie");
        btnOpenVerhuringenDeleteDialog.setEnabled(false);
        btnOpenVerhuringenDeleteDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenVerhuringenDeleteDialogActionPerformed(evt);
            }
        });

        btnOpenVerhuringenCreateDialog.setText("Nieuwe verhuring");
        btnOpenVerhuringenCreateDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenVerhuringenCreateDialogActionPerformed(evt);
            }
        });

        btnFromVerhuringenToFietsen.setText("Naar fietsen");
        btnFromVerhuringenToFietsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFromVerhuringenToFietsenActionPerformed(evt);
            }
        });

        btnFromVerhuringenToHuurders.setText("Naar huurders");
        btnFromVerhuringenToHuurders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFromVerhuringenToHuurdersActionPerformed(evt);
            }
        });

        btnFromVerhuringenToHerstellingen.setText("Naar herstellingen");
        btnFromVerhuringenToHerstellingen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFromVerhuringenToHerstellingenActionPerformed(evt);
            }
        });

        btnOpenVerhuringenDetailsDialog.setText("Details selectie");
        btnOpenVerhuringenDetailsDialog.setEnabled(false);
        btnOpenVerhuringenDetailsDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenVerhuringenDetailsDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVerhuringenLayout = new javax.swing.GroupLayout(pnlVerhuringen);
        pnlVerhuringen.setLayout(pnlVerhuringenLayout);
        pnlVerhuringenLayout.setHorizontalGroup(
            pnlVerhuringenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerhuringenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVerhuringenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVerhuringenLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlVerhuringenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFromVerhuringenToHuurders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFromVerhuringenToFietsen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenVerhuringenDeleteDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenVerhuringenEditDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenVerhuringenCreateDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFromVerhuringenToHerstellingen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenVerhuringenDetailsDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlVerhuringenLayout.createSequentialGroup()
                        .addGroup(pnlVerhuringenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVerhuringenList)
                            .addComponent(btnOpenVerhuringenSearchDialog))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlVerhuringenLayout.setVerticalGroup(
            pnlVerhuringenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerhuringenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVerhuringenList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlVerhuringenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlVerhuringenLayout.createSequentialGroup()
                        .addComponent(btnOpenVerhuringenEditDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenVerhuringenDeleteDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenVerhuringenDetailsDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenVerhuringenCreateDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(btnFromVerhuringenToFietsen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFromVerhuringenToHuurders)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFromVerhuringenToHerstellingen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOpenVerhuringenSearchDialog)
                .addContainerGap())
        );

        lblFietsenlist.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFietsenlist.setText("Recente fietsen");
        lblFietsenlist.setToolTipText("");

        lstFietsen.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstFietsen.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstFietsenValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstFietsen);

        btnOpenFietsenSearchDialog.setText("Zoek fiets");
        btnOpenFietsenSearchDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFietsenSearchDialogActionPerformed(evt);
            }
        });

        btnOpenFietsenEditDialog.setText("Edit selectie");
        btnOpenFietsenEditDialog.setEnabled(false);
        btnOpenFietsenEditDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFietsenEditDialogActionPerformed(evt);
            }
        });

        btnOpenFietsenDeleteDialog.setText("Verwijder selectie");
        btnOpenFietsenDeleteDialog.setEnabled(false);
        btnOpenFietsenDeleteDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFietsenDeleteDialogActionPerformed(evt);
            }
        });

        btnOpenFietsenDetailsDialog.setText("Details selectie");
        btnOpenFietsenDetailsDialog.setEnabled(false);
        btnOpenFietsenDetailsDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFietsenDetailsDialogActionPerformed(evt);
            }
        });

        btnOpenFietsenCreateDialog.setText("Nieuwe fiets");
        btnOpenFietsenCreateDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFietsenCreateDialogActionPerformed(evt);
            }
        });

        btnFromFietsenToVerhuringen.setText("Naar verhuringen");
        btnFromFietsenToVerhuringen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFromFietsenToVerhuringenActionPerformed(evt);
            }
        });

        btnFromFietsenToHerstellingen.setText("Naar herstellingen");
        btnFromFietsenToHerstellingen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFromFietsenToHerstellingenActionPerformed(evt);
            }
        });

        btnFromFietsenToHuurders.setText("Naar huurders");
        btnFromFietsenToHuurders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFromFietsenToHuurdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFietsenLayout = new javax.swing.GroupLayout(pnlFietsen);
        pnlFietsen.setLayout(pnlFietsenLayout);
        pnlFietsenLayout.setHorizontalGroup(
            pnlFietsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFietsenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFietsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFietsenLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlFietsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFromFietsenToHuurders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFromFietsenToVerhuringen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenFietsenDeleteDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenFietsenEditDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenFietsenCreateDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFromFietsenToHerstellingen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenFietsenDetailsDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlFietsenLayout.createSequentialGroup()
                        .addGroup(pnlFietsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFietsenlist)
                            .addComponent(btnOpenFietsenSearchDialog))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlFietsenLayout.setVerticalGroup(
            pnlFietsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFietsenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFietsenlist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFietsenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlFietsenLayout.createSequentialGroup()
                        .addComponent(btnOpenFietsenEditDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenFietsenDeleteDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenFietsenDetailsDialog)
                        .addGap(11, 11, 11)
                        .addComponent(btnOpenFietsenCreateDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(btnFromFietsenToVerhuringen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFromFietsenToHuurders)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFromFietsenToHerstellingen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOpenFietsenSearchDialog)
                .addContainerGap())
        );

        lblHuurderList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHuurderList.setText("Recente huurders");
        lblHuurderList.setToolTipText("");

        lstHuurders.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstHuurders.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstHuurdersValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstHuurders);

        btnOpenHuurdersSearchDialog.setText("Zoek huurder");
        btnOpenHuurdersSearchDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenHuurdersSearchDialogActionPerformed(evt);
            }
        });

        btnOpenHuurdersEditDialog.setText("Edit selectie");
        btnOpenHuurdersEditDialog.setEnabled(false);
        btnOpenHuurdersEditDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenHuurdersEditDialogActionPerformed(evt);
            }
        });

        btnOpenHuurdersDeleteDialog.setText("Verwijder selectie");
        btnOpenHuurdersDeleteDialog.setEnabled(false);
        btnOpenHuurdersDeleteDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenHuurdersDeleteDialogActionPerformed(evt);
            }
        });

        btnOpenHuurdersCreateDialog.setText("Nieuwe huurder");
        btnOpenHuurdersCreateDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenHuurdersCreateDialogActionPerformed(evt);
            }
        });

        btnFromHuurdersToVerhuringen.setText("Naar verhuringen");
        btnFromHuurdersToVerhuringen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFromHuurdersToVerhuringenActionPerformed(evt);
            }
        });

        btnFromHuurdersToHerstellingen.setText("Naar herstellingen");
        btnFromHuurdersToHerstellingen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFromHuurdersToHerstellingenActionPerformed(evt);
            }
        });

        btnFromHuurdersToFietsen.setText("Naar fietsen");
        btnFromHuurdersToFietsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFromHuurdersToFietsenActionPerformed(evt);
            }
        });

        btnOpenHuurdersDetailsDialog.setText("Details selectie");
        btnOpenHuurdersDetailsDialog.setEnabled(false);
        btnOpenHuurdersDetailsDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenHuurdersDetailsDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHuurdersLayout = new javax.swing.GroupLayout(pnlHuurders);
        pnlHuurders.setLayout(pnlHuurdersLayout);
        pnlHuurdersLayout.setHorizontalGroup(
            pnlHuurdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHuurdersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHuurdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHuurdersLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlHuurdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFromHuurdersToFietsen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFromHuurdersToVerhuringen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenHuurdersDeleteDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenHuurdersEditDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenHuurdersCreateDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFromHuurdersToHerstellingen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenHuurdersDetailsDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlHuurdersLayout.createSequentialGroup()
                        .addGroup(pnlHuurdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHuurderList)
                            .addComponent(btnOpenHuurdersSearchDialog))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlHuurdersLayout.setVerticalGroup(
            pnlHuurdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHuurdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHuurderList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHuurdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(pnlHuurdersLayout.createSequentialGroup()
                        .addComponent(btnOpenHuurdersEditDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenHuurdersDeleteDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenHuurdersDetailsDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenHuurdersCreateDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(btnFromHuurdersToVerhuringen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFromHuurdersToFietsen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFromHuurdersToHerstellingen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOpenHuurdersSearchDialog)
                .addContainerGap())
        );

        btnHerstellingenList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHerstellingenList.setText("Recente herstellingen");
        btnHerstellingenList.setToolTipText("");

        lstHerstellingen.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstHerstellingen.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstHerstellingenValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstHerstellingen);

        btnOpenHerstellingenSearchDialog.setText("Zoek herstelling");
        btnOpenHerstellingenSearchDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenHerstellingenSearchDialogActionPerformed(evt);
            }
        });

        btnOpenHerstellingenEditDialog.setText("Edit selectie");
        btnOpenHerstellingenEditDialog.setEnabled(false);
        btnOpenHerstellingenEditDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenHerstellingenEditDialogActionPerformed(evt);
            }
        });

        btnOpenHerstellingenDeleteDialog.setText("Verwijder selectie");
        btnOpenHerstellingenDeleteDialog.setEnabled(false);
        btnOpenHerstellingenDeleteDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenHerstellingenDeleteDialogActionPerformed(evt);
            }
        });

        btnOpenHerstellingenCreateDialog.setText("Nieuwe herstelling");
        btnOpenHerstellingenCreateDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenHerstellingenCreateDialogActionPerformed(evt);
            }
        });

        btnFromHerstellingenToVerhuringen.setText("Naar verhuringen");
        btnFromHerstellingenToVerhuringen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFromHerstellingenToVerhuringenActionPerformed(evt);
            }
        });

        btnFromHerstellingenToFietsen.setText("Naar fietsen");
        btnFromHerstellingenToFietsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFromHerstellingenToFietsenActionPerformed(evt);
            }
        });

        btnFromHerstellingentoHuurders.setText("Naar huurders");
        btnFromHerstellingentoHuurders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFromHerstellingentoHuurdersActionPerformed(evt);
            }
        });

        btnOpenHerstellingenDetailsDialog.setText("Details selectie");
        btnOpenHerstellingenDetailsDialog.setEnabled(false);
        btnOpenHerstellingenDetailsDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenHerstellingenDetailsDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHerstellingenLayout = new javax.swing.GroupLayout(pnlHerstellingen);
        pnlHerstellingen.setLayout(pnlHerstellingenLayout);
        pnlHerstellingenLayout.setHorizontalGroup(
            pnlHerstellingenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHerstellingenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHerstellingenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHerstellingenLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlHerstellingenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFromHerstellingentoHuurders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFromHerstellingenToVerhuringen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenHerstellingenDeleteDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenHerstellingenEditDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenHerstellingenCreateDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFromHerstellingenToFietsen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenHerstellingenDetailsDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlHerstellingenLayout.createSequentialGroup()
                        .addGroup(pnlHerstellingenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHerstellingenList)
                            .addComponent(btnOpenHerstellingenSearchDialog))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlHerstellingenLayout.setVerticalGroup(
            pnlHerstellingenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHerstellingenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHerstellingenList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHerstellingenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(pnlHerstellingenLayout.createSequentialGroup()
                        .addComponent(btnOpenHerstellingenEditDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenHerstellingenDeleteDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenHerstellingenDetailsDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenHerstellingenCreateDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(btnFromHerstellingenToVerhuringen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFromHerstellingentoHuurders)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFromHerstellingenToFietsen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOpenHerstellingenSearchDialog)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVerhuringen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlFietsen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlHuurders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlHerstellingen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVerhuringen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlFietsen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlHuurders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlHerstellingen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenVerhuringenSearchDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenVerhuringenSearchDialogActionPerformed
        VerhuringenSearchDialog dialog = new VerhuringenSearchDialog(this, true);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        updateVerhuringenList();
    }//GEN-LAST:event_btnOpenVerhuringenSearchDialogActionPerformed

    private void btnOpenVerhuringenEditDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenVerhuringenEditDialogActionPerformed
        ArrayList <Verhuring> verhuringenToEdit = new ArrayList <Verhuring> (lstVerhuringen.getSelectedValuesList());
        VerhuringenEditDialog dialog = new VerhuringenEditDialog(this, true);
        dialog.createTextFieldsAndSetVerhuringen(verhuringenToEdit);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        updateVerhuringenList();
    }//GEN-LAST:event_btnOpenVerhuringenEditDialogActionPerformed

    private void btnOpenVerhuringenDeleteDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenVerhuringenDeleteDialogActionPerformed
        ArrayList <Verhuring> verhuringenToDelete = new ArrayList <Verhuring> (lstVerhuringen.getSelectedValuesList());
        VerhuringenDeleteDialog dialog = new VerhuringenDeleteDialog(this, true);
        dialog.createTextFieldsAndSetVerhuringen(verhuringenToDelete);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        updateVerhuringenList();
    }//GEN-LAST:event_btnOpenVerhuringenDeleteDialogActionPerformed

    private void btnOpenVerhuringenCreateDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenVerhuringenCreateDialogActionPerformed
        VerhuringenCreateDialog dialog = new VerhuringenCreateDialog(this, true);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        updateVerhuringenList();
    }//GEN-LAST:event_btnOpenVerhuringenCreateDialogActionPerformed

    private void btnFromVerhuringenToFietsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFromVerhuringenToFietsenActionPerformed
        updateFietsenList();
        pnlVerhuringen.setVisible(false);
        pnlFietsen.setVisible(true);
    }//GEN-LAST:event_btnFromVerhuringenToFietsenActionPerformed

    private void btnFromVerhuringenToHuurdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFromVerhuringenToHuurdersActionPerformed
        updateHuurdersList();
        pnlVerhuringen.setVisible(false);
        pnlHuurders.setVisible(true);
    }//GEN-LAST:event_btnFromVerhuringenToHuurdersActionPerformed

    private void btnFromVerhuringenToHerstellingenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFromVerhuringenToHerstellingenActionPerformed
        updateHerstellingenList();
        pnlVerhuringen.setVisible(false);
        pnlHerstellingen.setVisible(true);
    }//GEN-LAST:event_btnFromVerhuringenToHerstellingenActionPerformed

    private void btnFromFietsenToVerhuringenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFromFietsenToVerhuringenActionPerformed
        updateVerhuringenList();
        pnlFietsen.setVisible(false);
        pnlVerhuringen.setVisible(true);
    }//GEN-LAST:event_btnFromFietsenToVerhuringenActionPerformed

    private void btnFromFietsenToHuurdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFromFietsenToHuurdersActionPerformed
        updateHuurdersList();
        pnlFietsen.setVisible(false);
        pnlHuurders.setVisible(true);
    }//GEN-LAST:event_btnFromFietsenToHuurdersActionPerformed

    private void btnFromFietsenToHerstellingenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFromFietsenToHerstellingenActionPerformed
        updateHerstellingenList();
        pnlFietsen.setVisible(false);
        pnlHerstellingen.setVisible(true);
    }//GEN-LAST:event_btnFromFietsenToHerstellingenActionPerformed

    private void btnFromHuurdersToVerhuringenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFromHuurdersToVerhuringenActionPerformed
        updateVerhuringenList();
        pnlHuurders.setVisible(false);
        pnlVerhuringen.setVisible(true);
    }//GEN-LAST:event_btnFromHuurdersToVerhuringenActionPerformed

    private void btnFromHuurdersToFietsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFromHuurdersToFietsenActionPerformed
        updateFietsenList();
        pnlHuurders.setVisible(false);
        pnlFietsen.setVisible(true);
    }//GEN-LAST:event_btnFromHuurdersToFietsenActionPerformed

    private void btnFromHuurdersToHerstellingenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFromHuurdersToHerstellingenActionPerformed
        updateHerstellingenList();
        pnlHuurders.setVisible(false);
        pnlHerstellingen.setVisible(true);
    }//GEN-LAST:event_btnFromHuurdersToHerstellingenActionPerformed

    private void btnFromHerstellingenToVerhuringenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFromHerstellingenToVerhuringenActionPerformed
        updateVerhuringenList();
        pnlHerstellingen.setVisible(false);
        pnlVerhuringen.setVisible(true);
    }//GEN-LAST:event_btnFromHerstellingenToVerhuringenActionPerformed

    private void btnFromHerstellingentoHuurdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFromHerstellingentoHuurdersActionPerformed
        updateHuurdersList();
        pnlHerstellingen.setVisible(false);
        pnlHuurders.setVisible(true);
    }//GEN-LAST:event_btnFromHerstellingentoHuurdersActionPerformed

    private void btnFromHerstellingenToFietsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFromHerstellingenToFietsenActionPerformed
        updateFietsenList();
        pnlHerstellingen.setVisible(false);
        pnlFietsen.setVisible(true);
    }//GEN-LAST:event_btnFromHerstellingenToFietsenActionPerformed

    private void lstVerhuringenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstVerhuringenValueChanged
        if (lstVerhuringen.isSelectionEmpty()) {
            btnOpenVerhuringenDeleteDialog.setEnabled(false);
            btnOpenVerhuringenEditDialog.setEnabled(false);
            btnOpenVerhuringenDetailsDialog.setEnabled(false);
        } else {
            btnOpenVerhuringenDeleteDialog.setEnabled(true);
            btnOpenVerhuringenEditDialog.setEnabled(true);
            btnOpenVerhuringenDetailsDialog.setEnabled(true);
        }
    }//GEN-LAST:event_lstVerhuringenValueChanged

    private void lstFietsenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstFietsenValueChanged
        if (lstFietsen.isSelectionEmpty()) {
            btnOpenFietsenDeleteDialog.setEnabled(false);
            btnOpenFietsenEditDialog.setEnabled(false);
            btnOpenFietsenDetailsDialog.setEnabled(false);
        } else {
            btnOpenFietsenDeleteDialog.setEnabled(true);
            btnOpenFietsenEditDialog.setEnabled(true);
            btnOpenFietsenDetailsDialog.setEnabled(true);
        }
    }//GEN-LAST:event_lstFietsenValueChanged

    private void lstHuurdersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstHuurdersValueChanged
        if (lstHuurders.isSelectionEmpty()) {
            btnOpenHuurdersDeleteDialog.setEnabled(false);
            btnOpenHuurdersEditDialog.setEnabled(false);
            btnOpenHuurdersDetailsDialog.setEnabled(false);
        } else {
            btnOpenHuurdersDeleteDialog.setEnabled(true);
            btnOpenHuurdersEditDialog.setEnabled(true);
            btnOpenHuurdersDetailsDialog.setEnabled(true);
        }
    }//GEN-LAST:event_lstHuurdersValueChanged

    private void lstHerstellingenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstHerstellingenValueChanged
        if (lstHerstellingen.isSelectionEmpty()) {
            btnOpenHerstellingenDeleteDialog.setEnabled(false);
            btnOpenHerstellingenEditDialog.setEnabled(false);
            btnOpenHerstellingenDetailsDialog.setEnabled(false);
        } else {
            btnOpenHerstellingenDeleteDialog.setEnabled(true);
            btnOpenHerstellingenEditDialog.setEnabled(true);
            btnOpenHerstellingenDetailsDialog.setEnabled(true);
        }
    }//GEN-LAST:event_lstHerstellingenValueChanged

    private void btnOpenVerhuringenDetailsDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenVerhuringenDetailsDialogActionPerformed
        ArrayList <Verhuring> verhuringenToShow = new ArrayList <Verhuring> (lstVerhuringen.getSelectedValuesList());
        VerhuringenDetailsDialog dialog = new VerhuringenDetailsDialog(this, true);
        dialog.createTextFieldsAndSetVerhuringen(verhuringenToShow);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        updateVerhuringenList();
    }//GEN-LAST:event_btnOpenVerhuringenDetailsDialogActionPerformed

    private void btnOpenFietsenSearchDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFietsenSearchDialogActionPerformed
        FietsenSearchDialog dialog = new FietsenSearchDialog(this, true);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        updateFietsenList();
    }//GEN-LAST:event_btnOpenFietsenSearchDialogActionPerformed

    private void btnOpenFietsenEditDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFietsenEditDialogActionPerformed
        ArrayList <Fiets> fietsenToEdit = new ArrayList <Fiets> (lstFietsen.getSelectedValuesList());
        FietsenEditDialog dialog = new FietsenEditDialog(this, true);
        dialog.createTextFieldsAndSetFietsen(fietsenToEdit);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        if(dialog.showDialog() == FietsenEditDialog.Resultaat.BEVESTIGD) {
            ArrayList<Fiets> gewijzigdeFietsen = dialog.getFietsen();
            for(Fiets gewijzigdeFiets : gewijzigdeFietsen){
                FietsDao.updateFiets(gewijzigdeFiets);
            }
        }
        updateFietsenList();
    }//GEN-LAST:event_btnOpenFietsenEditDialogActionPerformed

    private void btnOpenFietsenDeleteDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFietsenDeleteDialogActionPerformed
        ArrayList <Fiets> fietsenToDelete = new ArrayList <Fiets> (lstFietsen.getSelectedValuesList());
        
        
        ArrayList <Verhuring> existingVerhuringen = new ArrayList <Verhuring>();
        ArrayList <Herstelling> existingHerstellingen = new ArrayList <Herstelling>();
        for(Fiets fiets : fietsenToDelete) {
            for(Verhuring verhuring : VerhuringDao.getVerhuringenByFietsnummer(fiets.getFietsnummer())) {
                existingVerhuringen.add(verhuring);
            }
            for(Herstelling herstelling : HerstellingDao.getHerstellingenByFietsnummer(fiets.getFietsnummer())) {
                existingHerstellingen.add(herstelling);
            }
        }
        
        if(existingVerhuringen.size() > 0 || existingHerstellingen.size() > 0) {
            String message = "Onderstaande verhuringen en/of herstellingen zijn teruggevonden op de door u geselecteerde fietsen:\n\n";
            for(Verhuring verhuring: existingVerhuringen) {
                message += "Verhuring " + Integer.toString(verhuring.getVerhuringId()) + ": fiets " + Integer.toString(verhuring.getFietsnummer()) + ".\n";
            }
            for(Herstelling herstelling: existingHerstellingen) {
                message += "Herstelling " + Integer.toString(herstelling.getHerstellingId()) + ": fiets " + Integer.toString(herstelling.getFietsnummer()) + ".\n";
            }
            message += "\nU kunt de geselecteerde fietsen pas verwijderen, wanneer deze verhuringen en/of herstellingen verwijderd zijn.\nWenst u deze eerst te verwijderen?";
            Object[] options = {"Nee, verwijder niets.", "Ja, verwijder de verhuringen/herstellingen"};
            int choice = JOptionPane.showOptionDialog(this,
                                                      message,
                                                      "Verhuringen/herstellingen teruggevonden",
                                                      JOptionPane.YES_NO_OPTION,
                                                      JOptionPane.INFORMATION_MESSAGE,
                                                      null,
                                                      options,
                                                      options[0]);
            if (choice == 1) {
                for(Verhuring verhuring: existingVerhuringen) {
                    VerhuringDao.verwijderVerhuring(verhuring.getVerhuringId());
                }
                for(Herstelling herstelling: existingHerstellingen) {
                    DeelherstellingDao.verwijderDeelherstellingenByHerstellingId(herstelling.getHerstellingId());
                    HerstellingDao.verwijderHerstelling(herstelling.getHerstellingId());
                }
                
                FietsenDeleteDialog dialog = new FietsenDeleteDialog(this, true);
                dialog.createTextFieldsAndSetFietsen(fietsenToDelete);
                dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
                    if(dialog.showDialog() == FietsenDeleteDialog.Resultaat.BEVESTIGD) {
                    for(Fiets fietsToDelete : fietsenToDelete) {
                        FietsDao.verwijderFiets(fietsToDelete.getFietsnummer());
                    }
                }
                updateFietsenList();
            }
        } else {
            FietsenDeleteDialog dialog = new FietsenDeleteDialog(this, true);
            dialog.createTextFieldsAndSetFietsen(fietsenToDelete);
            dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
            
            if(dialog.showDialog() == FietsenDeleteDialog.Resultaat.BEVESTIGD) {
                for(Fiets fietsToDelete : fietsenToDelete) {
                    FietsDao.verwijderFiets(fietsToDelete.getFietsnummer());
                }
            }
            updateFietsenList();
        }
    }//GEN-LAST:event_btnOpenFietsenDeleteDialogActionPerformed

    private void btnOpenFietsenDetailsDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFietsenDetailsDialogActionPerformed
        ArrayList <Fiets> fietsenToShow = new ArrayList <Fiets> (lstFietsen.getSelectedValuesList());
        FietsenDetailsDialog dialog = new FietsenDetailsDialog(this, true);
        dialog.createTextFieldsAndSetFietsen(fietsenToShow);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        updateFietsenList();
    }//GEN-LAST:event_btnOpenFietsenDetailsDialogActionPerformed

    private void btnOpenFietsenCreateDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFietsenCreateDialogActionPerformed
        FietsenCreateDialog dialog = new FietsenCreateDialog(this, true);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        if(dialog.showDialog() == FietsenCreateDialog.Resultaat.BEVESTIGD) {
            Fiets nieuweFiets = dialog.getFiets();
            FietsDao.voegFietsToe(nieuweFiets);
        }
        updateFietsenList();
    }//GEN-LAST:event_btnOpenFietsenCreateDialogActionPerformed

    private void btnOpenHuurdersSearchDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenHuurdersSearchDialogActionPerformed
        HuurdersSearchDialog dialog = new HuurdersSearchDialog(this, true);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        updateHuurdersList();
    }//GEN-LAST:event_btnOpenHuurdersSearchDialogActionPerformed

    private void btnOpenHuurdersEditDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenHuurdersEditDialogActionPerformed
        ArrayList <Huurder> huurdersToEdit = new ArrayList <Huurder> (lstHuurders.getSelectedValuesList());
        HuurdersEditDialog dialog = new HuurdersEditDialog(this, true);
        dialog.createTextFieldsAndSetHuurders(huurdersToEdit);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        if(dialog.showDialog() == HuurdersEditDialog.Resultaat.BEVESTIGD) {
            for(Huurder gewijzigdeHuurder : dialog.getHuurders()) {
                HuurderDao.updateHuurder(gewijzigdeHuurder);
            }
        }
        updateHuurdersList();
    }//GEN-LAST:event_btnOpenHuurdersEditDialogActionPerformed

    private void btnOpenHuurdersDeleteDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenHuurdersDeleteDialogActionPerformed
        ArrayList <Huurder> huurdersToDelete = new ArrayList <Huurder> (lstHuurders.getSelectedValuesList());
                
        
        ArrayList <Verhuring> existingVerhuringen = new ArrayList <Verhuring>();
        ArrayList <Herstelling> existingHerstellingen = new ArrayList <Herstelling>();
        for(Huurder huurder : huurdersToDelete) {
            for(Verhuring verhuring : VerhuringDao.getVerhuringenByHuurderId(huurder.getHuurderId())) {
                existingVerhuringen.add(verhuring);
            }
            for(Herstelling herstelling : HerstellingDao.getHerstellingenByHuurderId(huurder.getHuurderId())) {
                existingHerstellingen.add(herstelling);
            }
        }
        
        if(existingVerhuringen.size() > 0 || existingHerstellingen.size() > 0) {
            String message = "Onderstaande verhuringen en/of herstellingen zijn teruggevonden op de door u geselecteerde huurders:\n\n";
            for(Verhuring verhuring: existingVerhuringen) {
                message += "Verhuring " + Integer.toString(verhuring.getVerhuringId()) + ": huurder " + Integer.toString(verhuring.getHuurderId()) + ".\n";
            }
            for(Herstelling herstelling: existingHerstellingen) {
                message += "Herstelling " + Integer.toString(herstelling.getHerstellingId()) + ": huurder " + Integer.toString(herstelling.getHuurderId()) + ".\n";
            }
            message += "\nU kunt de geselecteerde huurders pas verwijderen, wanneer deze verhuringen en/of herstellingen verwijderd zijn.\nWenst u deze eerst te verwijderen?";
            Object[] options = {"Nee, verwijder niets.", "Ja, verwijder de verhuringen/herstellingen"};
            int choice = JOptionPane.showOptionDialog(this,
                                                      message,
                                                      "Verhuringen/herstellingen teruggevonden",
                                                      JOptionPane.YES_NO_OPTION,
                                                      JOptionPane.INFORMATION_MESSAGE,
                                                      null,
                                                      options,
                                                      options[0]);
            if (choice == 1) {
                for(Verhuring verhuring: existingVerhuringen) {
                    VerhuringDao.verwijderVerhuring(verhuring.getVerhuringId());
                }
                for(Herstelling herstelling: existingHerstellingen) {
                    DeelherstellingDao.verwijderDeelherstellingenByHerstellingId(herstelling.getHerstellingId());
                    HerstellingDao.verwijderHerstelling(herstelling.getHerstellingId());
                }
                
                HuurdersDeleteDialog dialog = new HuurdersDeleteDialog(this, true);
                dialog.createTextFieldsAndSetHuurders(huurdersToDelete);
                dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
                if(dialog.showDialog() == HuurdersDeleteDialog.Resultaat.BEVESTIGD) {
                    for(Huurder huurder: huurdersToDelete) {
                        HuurderDao.verwijderHuurder(huurder.getHuurderId());
                    }
                }
                updateHuurdersList();
            }
        } else {
            HuurdersDeleteDialog dialog = new HuurdersDeleteDialog(this, true);
            dialog.createTextFieldsAndSetHuurders(huurdersToDelete);
            dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
            if(dialog.showDialog() == HuurdersDeleteDialog.Resultaat.BEVESTIGD) {
                for(Huurder huurder: huurdersToDelete) {
                    HuurderDao.verwijderHuurder(huurder.getHuurderId());
                }
            }
            updateHuurdersList();
        }
    }//GEN-LAST:event_btnOpenHuurdersDeleteDialogActionPerformed

    private void btnOpenHuurdersDetailsDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenHuurdersDetailsDialogActionPerformed
        ArrayList <Huurder> huurdersToShow = new ArrayList <Huurder> (lstHuurders.getSelectedValuesList());
        HuurdersDetailsDialog dialog = new HuurdersDetailsDialog(this, true);
        dialog.createTextFieldsAndSetHuurders(huurdersToShow);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        updateHuurdersList();
    }//GEN-LAST:event_btnOpenHuurdersDetailsDialogActionPerformed

    private void btnOpenHuurdersCreateDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenHuurdersCreateDialogActionPerformed
        HuurdersCreateDialog dialog = new HuurdersCreateDialog(this, true);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        if(dialog.showDialog() == HuurdersCreateDialog.Resultaat.BEVESTIGD) {
            HuurderDao.voegHuurderToe(dialog.getHuurder());
        }
        updateHuurdersList();
    }//GEN-LAST:event_btnOpenHuurdersCreateDialogActionPerformed

    private void btnOpenHerstellingenSearchDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenHerstellingenSearchDialogActionPerformed
        HerstellingenSearchDialog dialog = new HerstellingenSearchDialog(this, true);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        updateHerstellingenList();
    }//GEN-LAST:event_btnOpenHerstellingenSearchDialogActionPerformed

    private void btnOpenHerstellingenEditDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenHerstellingenEditDialogActionPerformed
        ArrayList <Herstelling> herstellingenToEdit = new ArrayList <Herstelling> (lstHerstellingen.getSelectedValuesList());
        HerstellingenEditDialog dialog = new HerstellingenEditDialog(this, true);
        dialog.createTextFieldsAndSetHerstellingen(herstellingenToEdit);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        updateHerstellingenList();
    }//GEN-LAST:event_btnOpenHerstellingenEditDialogActionPerformed

    private void btnOpenHerstellingenDeleteDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenHerstellingenDeleteDialogActionPerformed
        ArrayList <Herstelling> herstellingenToDelete = new ArrayList <Herstelling> (lstHerstellingen.getSelectedValuesList());
        HerstellingenDeleteDialog dialog = new HerstellingenDeleteDialog(this, true);
        dialog.createTextFieldsAndSetHerstellingen(herstellingenToDelete);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        updateHerstellingenList();
    }//GEN-LAST:event_btnOpenHerstellingenDeleteDialogActionPerformed

    private void btnOpenHerstellingenDetailsDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenHerstellingenDetailsDialogActionPerformed
        ArrayList <Herstelling> herstellingenToShow = new ArrayList <Herstelling> (lstHerstellingen.getSelectedValuesList());
        HerstellingenDetailsDialog dialog = new HerstellingenDetailsDialog(this, true);
        dialog.createTextFieldsAndSetHerstellingen(herstellingenToShow);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        updateHerstellingenList();
    }//GEN-LAST:event_btnOpenHerstellingenDetailsDialogActionPerformed

    private void btnOpenHerstellingenCreateDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenHerstellingenCreateDialogActionPerformed
        HerstellingenCreateDialog dialog = new HerstellingenCreateDialog(this, true);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        updateHerstellingenList();
    }//GEN-LAST:event_btnOpenHerstellingenCreateDialogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fietsverhuurGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fietsverhuurGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fietsverhuurGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fietsverhuurGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fietsverhuurGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFromFietsenToHerstellingen;
    private javax.swing.JButton btnFromFietsenToHuurders;
    private javax.swing.JButton btnFromFietsenToVerhuringen;
    private javax.swing.JButton btnFromHerstellingenToFietsen;
    private javax.swing.JButton btnFromHerstellingenToVerhuringen;
    private javax.swing.JButton btnFromHerstellingentoHuurders;
    private javax.swing.JButton btnFromHuurdersToFietsen;
    private javax.swing.JButton btnFromHuurdersToHerstellingen;
    private javax.swing.JButton btnFromHuurdersToVerhuringen;
    private javax.swing.JButton btnFromVerhuringenToFietsen;
    private javax.swing.JButton btnFromVerhuringenToHerstellingen;
    private javax.swing.JButton btnFromVerhuringenToHuurders;
    private javax.swing.JLabel btnHerstellingenList;
    private javax.swing.JButton btnOpenFietsenCreateDialog;
    private javax.swing.JButton btnOpenFietsenDeleteDialog;
    private javax.swing.JButton btnOpenFietsenDetailsDialog;
    private javax.swing.JButton btnOpenFietsenEditDialog;
    private javax.swing.JButton btnOpenFietsenSearchDialog;
    private javax.swing.JButton btnOpenHerstellingenCreateDialog;
    private javax.swing.JButton btnOpenHerstellingenDeleteDialog;
    private javax.swing.JButton btnOpenHerstellingenDetailsDialog;
    private javax.swing.JButton btnOpenHerstellingenEditDialog;
    private javax.swing.JButton btnOpenHerstellingenSearchDialog;
    private javax.swing.JButton btnOpenHuurdersCreateDialog;
    private javax.swing.JButton btnOpenHuurdersDeleteDialog;
    private javax.swing.JButton btnOpenHuurdersDetailsDialog;
    private javax.swing.JButton btnOpenHuurdersEditDialog;
    private javax.swing.JButton btnOpenHuurdersSearchDialog;
    private javax.swing.JButton btnOpenVerhuringenCreateDialog;
    private javax.swing.JButton btnOpenVerhuringenDeleteDialog;
    private javax.swing.JButton btnOpenVerhuringenDetailsDialog;
    private javax.swing.JButton btnOpenVerhuringenEditDialog;
    private javax.swing.JButton btnOpenVerhuringenSearchDialog;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblFietsenlist;
    private javax.swing.JLabel lblHuurderList;
    private javax.swing.JLabel lblVerhuringenList;
    private javax.swing.JList lstFietsen;
    private javax.swing.JList lstHerstellingen;
    private javax.swing.JList lstHuurders;
    private javax.swing.JList lstVerhuringen;
    private javax.swing.JPanel pnlFietsen;
    private javax.swing.JPanel pnlHerstellingen;
    private javax.swing.JPanel pnlHuurders;
    private javax.swing.JPanel pnlVerhuringen;
    // End of variables declaration//GEN-END:variables
}
