/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fietsverhuur.swing;

import fietsverhuur.model.*;
import fietsverhuur.dao.*;
import java.util.ArrayList;

/**
 *
 * @author Myra
 */
public class FietsenCreateDialog extends javax.swing.JDialog {

    /**
     * Creates new form VerhuringenCreateGUIb
     */
    private Resultaat formulierResultaat;

    public Resultaat getFormulierResultaat() {
        return formulierResultaat;
    }
    
    public enum Resultaat{
        GEANNULEERD,
        BEVESTIGD
    }
    
    public FietsenCreateDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ArrayList<Fiets> lst = FietsDao.getFietsen();
        int fietsnummer = 1 + lst.get(0).getFietsnummer();
        txtFietsnummer.setText(Integer.toString(fietsnummer));
    }
    
    public Resultaat showDialog() {
        this.setModal(true);
        this.setVisible(true);
        return this.formulierResultaat;
    }

    public Fiets getFiets() {
        Fiets resultaat;
        
        String gender = cmbGender.getModel().getSelectedItem().toString();
        String fietstype = cmbFietstype.getModel().getSelectedItem().toString();
        int aantalVitessen;
        if(!txtAantalVitessen.getText().equals("")) {
            aantalVitessen = Integer.parseInt(txtAantalVitessen.getText());
        } else {
            aantalVitessen = 0;
        }
        String dikteBand = cmbDikteBand.getModel().getSelectedItem().toString();
        if(dikteBand.equals("Kies dikte...")) {
            dikteBand = "";
        }
        String kleur = txtKleur.getText();
        int verhuurpuntId = Integer.parseInt(txtVerhuurpuntId.getText());

        resultaat = new Fiets(gender, fietstype, aantalVitessen, dikteBand, kleur, verhuurpuntId);
        return resultaat;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDikteBand = new javax.swing.JLabel();
        lblAantalVitessen = new javax.swing.JLabel();
        btnCloseGUI = new javax.swing.JButton();
        btnSaveDataAndCloseGUI = new javax.swing.JButton();
        lblTitel = new javax.swing.JLabel();
        txtFietsnummer = new javax.swing.JTextField();
        lblFoutmelding = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblFietstype = new javax.swing.JLabel();
        lblFietsnummer = new javax.swing.JLabel();
        txtVerhuurpuntId = new javax.swing.JTextField();
        lblVerhuurpuntId = new javax.swing.JLabel();
        txtAantalVitessen = new javax.swing.JTextField();
        lblKleur = new javax.swing.JLabel();
        txtKleur = new javax.swing.JTextField();
        cmbFietstype = new javax.swing.JComboBox();
        cmbDikteBand = new javax.swing.JComboBox();
        cmbGender = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDikteBand.setText("Dikte Band");

        lblAantalVitessen.setText("Aantal Vitessen");

        btnCloseGUI.setText("Annuleren");
        btnCloseGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseGUIActionPerformed(evt);
            }
        });

        btnSaveDataAndCloseGUI.setText("Maak fiets aan");
        btnSaveDataAndCloseGUI.setToolTipText("");
        btnSaveDataAndCloseGUI.setEnabled(false);
        btnSaveDataAndCloseGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDataAndCloseGUIActionPerformed(evt);
            }
        });

        lblTitel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTitel.setText("Nieuwe fiets");

        txtFietsnummer.setEnabled(false);

        lblFoutmelding.setText(" ");

        lblGender.setText("Gender*");

        lblFietstype.setText("Fietstype*");

        lblFietsnummer.setText("Fietsnummer");

        txtVerhuurpuntId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVerhuurpuntIdKeyReleased(evt);
            }
        });

        lblVerhuurpuntId.setText("VerhuurpuntID*");

        txtAantalVitessen.setEnabled(false);
        txtAantalVitessen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAantalVitessenKeyReleased(evt);
            }
        });

        lblKleur.setText("Kleur");

        txtKleur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKleurKeyReleased(evt);
            }
        });

        cmbFietstype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "stadsfiets", "sportfiets" }));
        cmbFietstype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFietstypeItemStateChanged(evt);
            }
        });

        cmbDikteBand.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kies dikte...", "dun", "middel", "dik" }));
        cmbDikteBand.setEnabled(false);

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mannelijk", "vrouwelijk", "unisex" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAantalVitessen)
                            .addComponent(cmbGender, 0, 115, Short.MAX_VALUE)
                            .addComponent(lblGender)
                            .addComponent(txtAantalVitessen))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDikteBand)
                                    .addComponent(cmbDikteBand, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKleur)
                                    .addComponent(txtKleur, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFietstype)
                                    .addComponent(cmbFietstype, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVerhuurpuntId)
                                    .addComponent(txtVerhuurpuntId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lblFietsnummer)
                    .addComponent(txtFietsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoutmelding)
                    .addComponent(lblTitel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseGUI)
                .addGap(30, 30, 30)
                .addComponent(btnSaveDataAndCloseGUI)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFietsnummer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFietsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFietstype)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFietstype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVerhuurpuntId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVerhuurpuntId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDikteBand)
                            .addComponent(lblAantalVitessen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAantalVitessen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDikteBand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKleur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKleur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblFoutmelding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCloseGUI)
                    .addComponent(btnSaveDataAndCloseGUI))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseGUIActionPerformed
        this.formulierResultaat = Resultaat.GEANNULEERD;
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseGUIActionPerformed

    private void btnSaveDataAndCloseGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDataAndCloseGUIActionPerformed
        this.formulierResultaat = Resultaat.BEVESTIGD;
        this.setVisible(false);
    }//GEN-LAST:event_btnSaveDataAndCloseGUIActionPerformed

    private void txtVerhuurpuntIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVerhuurpuntIdKeyReleased
        enableDisableOpslaanButton();
    }//GEN-LAST:event_txtVerhuurpuntIdKeyReleased

    private void txtAantalVitessenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAantalVitessenKeyReleased
        enableDisableOpslaanButton();
    }//GEN-LAST:event_txtAantalVitessenKeyReleased

    private void txtKleurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKleurKeyReleased
        enableDisableOpslaanButton();
    }//GEN-LAST:event_txtKleurKeyReleased

    private void cmbFietstypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFietstypeItemStateChanged
        if(cmbFietstype.getModel().getSelectedItem().equals("stadsfiets")) {
            txtAantalVitessen.setEnabled(false);
            cmbDikteBand.setEnabled(false);
            txtKleur.setEnabled(true);
        } else {
            txtAantalVitessen.setEnabled(true);
            cmbDikteBand.setEnabled(true);
            txtKleur.setEnabled(false);
        }
    }//GEN-LAST:event_cmbFietstypeItemStateChanged

    public void enableDisableOpslaanButton() {
        if(txtVerhuurpuntId.getText().equals("")) {
            btnSaveDataAndCloseGUI.setEnabled(false);
            lblFoutmelding.setText("Vul a.u.b. alle verplichte velden in.");
        } else {
            if(CheckUserInput.doesVerhuurpuntIdExist(txtVerhuurpuntId.getText(), lblFoutmelding)){
                if(txtAantalVitessen.getText().equals("")|| CheckUserInput.isStringInteger(txtAantalVitessen.getText())) {
                    btnSaveDataAndCloseGUI.setEnabled(true);
                    lblFoutmelding.setText("");
                } else {
                    btnSaveDataAndCloseGUI.setEnabled(false);
                    lblFoutmelding.setText("Vul a.u.b. een geldig aantal vitessen in, of laat het tekstveld leeg.");
                }
            } else {
                btnSaveDataAndCloseGUI.setEnabled(false);
            }
        }
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FietsenCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FietsenCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FietsenCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FietsenCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FietsenCreateDialog dialog = new FietsenCreateDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseGUI;
    private javax.swing.JButton btnSaveDataAndCloseGUI;
    private javax.swing.JComboBox cmbDikteBand;
    private javax.swing.JComboBox cmbFietstype;
    private javax.swing.JComboBox cmbGender;
    private javax.swing.JLabel lblAantalVitessen;
    private javax.swing.JLabel lblDikteBand;
    private javax.swing.JLabel lblFietsnummer;
    private javax.swing.JLabel lblFietstype;
    private javax.swing.JLabel lblFoutmelding;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblKleur;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblVerhuurpuntId;
    private javax.swing.JTextField txtAantalVitessen;
    private javax.swing.JTextField txtFietsnummer;
    private javax.swing.JTextField txtKleur;
    private javax.swing.JTextField txtVerhuurpuntId;
    // End of variables declaration//GEN-END:variables
}
