/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fietsverhuur.swing;

import fietsverhuur.dao.*;
import fietsverhuur.model.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Myra
 */
public class HerstellingenSearchDialog extends javax.swing.JDialog {

    private DefaultListModel<Herstelling> herstellingenModel;
    
    public HerstellingenSearchDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        herstellingenModel = new DefaultListModel<Herstelling>();
        lstZoekresultaten.setModel(herstellingenModel);
    }
    
    public void showDialog() {
        this.setModal(true);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCloseThisGUI = new javax.swing.JButton();
        lblHerstellingId = new javax.swing.JLabel();
        txtHuurderId = new javax.swing.JTextField();
        lblBedragTot = new javax.swing.JLabel();
        txtKostprijsMax = new javax.swing.JTextField();
        lblZoekresultatenList = new javax.swing.JLabel();
        btnSearchHerstellingen = new javax.swing.JButton();
        lblTitel = new javax.swing.JLabel();
        btnOpenHerstellingenEditDialog = new javax.swing.JButton();
        btnOpenHerstellingenDeleteDialog = new javax.swing.JButton();
        txtHerstellingId = new javax.swing.JTextField();
        lblKostprijs = new javax.swing.JLabel();
        lblMeldingsdatum = new javax.swing.JLabel();
        txtKostprijsMin = new javax.swing.JTextField();
        txtMeldingsdatum = new javax.swing.JTextField();
        lblDefectnummer = new javax.swing.JLabel();
        txtDefectnummer = new javax.swing.JTextField();
        lblFietsnummer = new javax.swing.JLabel();
        txtFietsnummer = new javax.swing.JTextField();
        lblHuurderId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstZoekresultaten = new javax.swing.JList();
        lblFoutmelding = new javax.swing.JLabel();
        btnOpenHerstellingenDetailsDialog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCloseThisGUI.setText("Sluit venster");
        btnCloseThisGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseThisGUIActionPerformed(evt);
            }
        });

        lblHerstellingId.setText("HerstellingId");

        txtHuurderId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHuurderIdKeyReleased(evt);
            }
        });

        lblBedragTot.setText("tot");

        txtKostprijsMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKostprijsMaxKeyReleased(evt);
            }
        });

        lblZoekresultatenList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblZoekresultatenList.setText("Resultaten:");

        btnSearchHerstellingen.setText("Zoek herstelling");
        btnSearchHerstellingen.setEnabled(false);
        btnSearchHerstellingen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchHerstellingenActionPerformed(evt);
            }
        });

        lblTitel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTitel.setText("Zoek herstellingen");
        lblTitel.setToolTipText("");

        btnOpenHerstellingenEditDialog.setText("Details/Edit selectie");
        btnOpenHerstellingenEditDialog.setEnabled(false);
        btnOpenHerstellingenEditDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenHerstellingenEditDialogActionPerformed(evt);
            }
        });

        btnOpenHerstellingenDeleteDialog.setText("Verwijder selectie");
        btnOpenHerstellingenDeleteDialog.setEnabled(false);
        btnOpenHerstellingenDeleteDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenHerstellingenDeleteDialogActionPerformed(evt);
            }
        });

        txtHerstellingId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHerstellingIdKeyReleased(evt);
            }
        });

        lblKostprijs.setText("Kostprijs (€)");

        lblMeldingsdatum.setText("Meldingsdatum");

        txtKostprijsMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKostprijsMinKeyReleased(evt);
            }
        });

        txtMeldingsdatum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMeldingsdatumKeyReleased(evt);
            }
        });

        lblDefectnummer.setText("Defectnummer");

        txtDefectnummer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDefectnummerKeyReleased(evt);
            }
        });

        lblFietsnummer.setText("Fietsnummer");

        txtFietsnummer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFietsnummerKeyReleased(evt);
            }
        });

        lblHuurderId.setText("HuurderId");

        lstZoekresultaten.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstZoekresultatenValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstZoekresultaten);

        lblFoutmelding.setText(" ");

        btnOpenHerstellingenDetailsDialog.setText("Details selectie");
        btnOpenHerstellingenDetailsDialog.setEnabled(false);
        btnOpenHerstellingenDetailsDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenHerstellingenDetailsDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOpenHerstellingenDeleteDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenHerstellingenEditDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenHerstellingenDetailsDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCloseThisGUI)
                            .addComponent(lblZoekresultatenList)
                            .addComponent(lblTitel)
                            .addComponent(btnSearchHerstellingen)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHerstellingId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHerstellingId))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMeldingsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMeldingsdatum))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDefectnummer)
                                    .addComponent(txtDefectnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblHuurderId)
                                    .addComponent(txtHuurderId, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFietsnummer)
                                    .addComponent(txtFietsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKostprijs)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtKostprijsMin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblBedragTot)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtKostprijsMax, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblFoutmelding))
                        .addGap(0, 124, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHerstellingId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMeldingsdatum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDefectnummer, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMeldingsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHerstellingId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDefectnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHuurderId)
                            .addComponent(lblFietsnummer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHuurderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFietsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblKostprijs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKostprijsMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBedragTot)
                            .addComponent(txtKostprijsMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnSearchHerstellingen)
                .addGap(18, 18, 18)
                .addComponent(lblFoutmelding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblZoekresultatenList, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpenHerstellingenEditDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenHerstellingenDeleteDialog)
                        .addGap(11, 11, 11)
                        .addComponent(btnOpenHerstellingenDetailsDialog)))
                .addGap(18, 18, 18)
                .addComponent(btnCloseThisGUI)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHuurderIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHuurderIdKeyReleased
        if(checkIfEmpty(txtHuurderId)) {
            btnSearchHerstellingen.setEnabled(false);
        } else {
            if(CheckUserInput.doesHuurderIdExist(txtHuurderId.getText(), lblFoutmelding)) {
                btnSearchHerstellingen.setEnabled(true);
            } else {
                btnSearchHerstellingen.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtHuurderIdKeyReleased

    private void txtKostprijsMaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKostprijsMaxKeyReleased
         if(checkIfEmpty(txtKostprijsMax)) {
            btnSearchHerstellingen.setEnabled(false);
        } else {
            if(CheckUserInput.isStringDouble(txtKostprijsMax.getText())) {
                btnSearchHerstellingen.setEnabled(true);
                lblFoutmelding.setText("");
            } else {
                btnSearchHerstellingen.setEnabled(false);
                lblFoutmelding.setText("Vul a.u.b. een geldig bedrag in.");
            }
        }
    }//GEN-LAST:event_txtKostprijsMaxKeyReleased

    private void txtHerstellingIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHerstellingIdKeyReleased
        if(checkIfEmpty(txtHerstellingId)) {
            btnSearchHerstellingen.setEnabled(false);
        } else {
            if(CheckUserInput.isStringInteger(txtHerstellingId.getText())) {
                btnSearchHerstellingen.setEnabled(true);
                lblFoutmelding.setText("");
            } else {
                btnSearchHerstellingen.setEnabled(false);
                lblFoutmelding.setText("Vul a.u.b. een geldig nummer in.");
            }
        }
    }//GEN-LAST:event_txtHerstellingIdKeyReleased

    private void txtKostprijsMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKostprijsMinKeyReleased
        if(checkIfEmpty(txtKostprijsMin)) {
            btnSearchHerstellingen.setEnabled(false);
        } else {
            if(CheckUserInput.isStringDouble(txtKostprijsMin.getText())) {
                btnSearchHerstellingen.setEnabled(true);
                lblFoutmelding.setText("");
            } else {
                btnSearchHerstellingen.setEnabled(false);
                lblFoutmelding.setText("Vul a.u.b. een geldig bedrag in.");
            }
        }
    }//GEN-LAST:event_txtKostprijsMinKeyReleased

    private void txtMeldingsdatumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMeldingsdatumKeyReleased
        if(checkIfEmpty(txtMeldingsdatum)) {
            btnSearchHerstellingen.setEnabled(false);
        } else {
            if(CheckUserInput.isDateParsable(txtMeldingsdatum.getText(), lblFoutmelding)) {
                btnSearchHerstellingen.setEnabled(true);
            } else {
                btnSearchHerstellingen.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtMeldingsdatumKeyReleased

    private void txtDefectnummerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDefectnummerKeyReleased
        if(checkIfEmpty(txtDefectnummer)) {
            btnSearchHerstellingen.setEnabled(false);
        } else {
             if(CheckUserInput.doesDefectnummerExist(txtDefectnummer.getText(), lblFoutmelding)) {
                 btnSearchHerstellingen.setEnabled(true);
             } else {
                 btnSearchHerstellingen.setEnabled(false);
             }
         }
    }//GEN-LAST:event_txtDefectnummerKeyReleased

    private void txtFietsnummerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFietsnummerKeyReleased
        if(checkIfEmpty(txtFietsnummer)) {
            btnSearchHerstellingen.setEnabled(false);
        } else {
            if(CheckUserInput.doesFietsnummerExist(txtFietsnummer.getText(), lblFoutmelding)) {
                btnSearchHerstellingen.setEnabled(true);
            } else {
                btnSearchHerstellingen.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtFietsnummerKeyReleased

    private void btnCloseThisGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseThisGUIActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseThisGUIActionPerformed

    private void btnOpenHerstellingenEditDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenHerstellingenEditDialogActionPerformed
        ArrayList <Herstelling> herstellingenToEdit = new ArrayList <Herstelling> (lstZoekresultaten.getSelectedValuesList());
        JFrame frame= (JFrame) SwingUtilities.getWindowAncestor(this);
        HerstellingenEditDialog dialog = new HerstellingenEditDialog(frame, true);
        dialog.createTextFieldsAndSetHerstellingen(herstellingenToEdit);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        btnSearchHerstellingenActionPerformed(evt);
    }//GEN-LAST:event_btnOpenHerstellingenEditDialogActionPerformed

    private void btnOpenHerstellingenDeleteDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenHerstellingenDeleteDialogActionPerformed
        ArrayList <Herstelling> herstellingenToDelete = new ArrayList <Herstelling> (lstZoekresultaten.getSelectedValuesList());
        JFrame frame= (JFrame) SwingUtilities.getWindowAncestor(this);
        HerstellingenDeleteDialog dialog = new HerstellingenDeleteDialog(frame, true);
        dialog.createTextFieldsAndSetHerstellingen(herstellingenToDelete);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        btnSearchHerstellingenActionPerformed(evt);
    }//GEN-LAST:event_btnOpenHerstellingenDeleteDialogActionPerformed

    private void btnSearchHerstellingenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchHerstellingenActionPerformed
        herstellingenModel.clear();
        if(txtHerstellingId.isEnabled()) {
            int herstellingid = Integer.parseInt(txtHerstellingId.getText());
            Herstelling gevondenHerstelling = HerstellingDao.getHerstellingById(herstellingid);
            herstellingenModel.addElement(gevondenHerstelling);
        }
        if(txtMeldingsdatum.isEnabled()) {
            try {
                Date meldingsdatum = Calculate.df.parse(txtMeldingsdatum.getText());
                ArrayList<Herstelling> gevondenHerstellingenLijst = HerstellingDao.getHerstellingenByMeldingsdatum(meldingsdatum);
                for(Herstelling gevondenHerstelling : gevondenHerstellingenLijst) {
                    herstellingenModel.addElement(gevondenHerstelling);
                }
                
            } catch (ParseException ex) {
                lblFoutmelding.setText("Gelieve een geldige datum in te voeren.");
            }
        }
        if(txtHuurderId.isEnabled()) {
            int huurderId = Integer.parseInt(txtHuurderId.getText());
            ArrayList<Herstelling> gevondenHerstellingenLijst = HerstellingDao.getHerstellingenByHuurderId(huurderId);
            for(Herstelling gevondenHerstelling : gevondenHerstellingenLijst) {
                herstellingenModel.addElement(gevondenHerstelling);
            }
        }
        if(txtFietsnummer.isEnabled()) {
            int fietsnummer = Integer.parseInt(txtFietsnummer.getText());
            ArrayList<Herstelling> gevondenHerstellingenLijst = HerstellingDao.getHerstellingenByFietsnummer(fietsnummer);
            for(Herstelling gevondenHerstelling : gevondenHerstellingenLijst) {
                herstellingenModel.addElement(gevondenHerstelling);
            }
        }
        if(txtDefectnummer.isEnabled()) {
            int defectnummer = Integer.parseInt(txtDefectnummer.getText());
            ArrayList<Deelherstelling> gevondenDeelherstellingenLijst = DeelherstellingDao.getDeelherstellingenByDefectnummer(defectnummer);
            for(Deelherstelling gevondenDeelherstelling : gevondenDeelherstellingenLijst) {
                int herstellingId = gevondenDeelherstelling.getHerstellingId();
                Herstelling gevondenHerstelling = HerstellingDao.getHerstellingById(herstellingId);
                herstellingenModel.addElement(gevondenHerstelling);
            }
        }
        if(txtKostprijsMin.isEnabled()) {
            double kostprijsMin = 0;
            double kostprijsMax = 99999;
            if(!txtKostprijsMin.getText().equals("")) {
                kostprijsMin = Integer.parseInt(txtKostprijsMin.getText());
            }
            if(!txtKostprijsMax.getText().equals("")) {
                kostprijsMax = Integer.parseInt(txtKostprijsMax.getText());
            }
            ArrayList<Herstelling> herstellingenlist = HerstellingDao.getHerstellingen();
            for(Herstelling currentHerstelling : herstellingenlist) {
                ArrayList<Integer> defectnummers = new ArrayList<Integer>();
                ArrayList<Deelherstelling> gevondenDeelherstellingen = DeelherstellingDao.getDeelherstellingenByHerstellingId(currentHerstelling.getHerstellingId());
                for(Deelherstelling currentDeelherstelling : gevondenDeelherstellingen) {
                    defectnummers.add(currentDeelherstelling.getDefectnummer());
                }
                double kostprijs = Calculate.calculateHerstellingKostprijs(defectnummers);
                if(kostprijsMin <= kostprijs && kostprijsMax > kostprijs) {
                    herstellingenModel.addElement(currentHerstelling);
                }
            }
            
        }
    }//GEN-LAST:event_btnSearchHerstellingenActionPerformed

    private void lstZoekresultatenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstZoekresultatenValueChanged
        if (lstZoekresultaten.isSelectionEmpty()) {
            btnOpenHerstellingenDeleteDialog.setEnabled(false);
            btnOpenHerstellingenEditDialog.setEnabled(false);
            btnOpenHerstellingenDetailsDialog.setEnabled(false);
        } else {
            btnOpenHerstellingenDeleteDialog.setEnabled(true);
            btnOpenHerstellingenEditDialog.setEnabled(true);
            btnOpenHerstellingenDetailsDialog.setEnabled(true);
        }
    }//GEN-LAST:event_lstZoekresultatenValueChanged

    private void btnOpenHerstellingenDetailsDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenHerstellingenDetailsDialogActionPerformed
        ArrayList <Herstelling> herstellingenToShow = new ArrayList <Herstelling> (lstZoekresultaten.getSelectedValuesList());
        JFrame frame= (JFrame) SwingUtilities.getWindowAncestor(this);
        HerstellingenDetailsDialog dialog = new HerstellingenDetailsDialog(frame, true);
        dialog.createTextFieldsAndSetHerstellingen(herstellingenToShow);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
    }//GEN-LAST:event_btnOpenHerstellingenDetailsDialogActionPerformed

    public void setAllOtherTextFields(boolean status, javax.swing.JTextField textfield1, javax.swing.JTextField textfield2) {
        ArrayList <javax.swing.JTextField> textfields = new ArrayList<>(9);
        textfields.add(txtHerstellingId);
        textfields.add(txtMeldingsdatum);
        textfields.add(txtDefectnummer);
        textfields.add(txtHuurderId);
        textfields.add(txtFietsnummer);
        textfields.add(txtKostprijsMin);
        textfields.add(txtKostprijsMax);
        for(javax.swing.JTextField currenttextfield : textfields) {
            if(currenttextfield != textfield1 && currenttextfield != textfield2) {
                currenttextfield.setEnabled(status);
            }
        }
    }
    public boolean checkIfEmpty(javax.swing.JTextField currenttextfield) {
        boolean hasTwinTextfield = false;
        boolean noTextInTwintextfield = true;
        javax.swing.JTextField twintextfield = null;
        
        if(currenttextfield == txtKostprijsMin) {twintextfield = txtKostprijsMax; hasTwinTextfield = true;}
        if(currenttextfield == txtKostprijsMax) {twintextfield = txtKostprijsMin; hasTwinTextfield = true;}
        
        if(hasTwinTextfield) {
            if(!twintextfield.getText().equals("")) {
                noTextInTwintextfield = false;
            }
        }
        
        if(currenttextfield.getText().equals("") && noTextInTwintextfield) {
            setAllOtherTextFields(true, currenttextfield, currenttextfield);
            lblFoutmelding.setText("");
            return true;
        } else {
            if(hasTwinTextfield) {
                setAllOtherTextFields(false, currenttextfield, twintextfield);
            } else {
                setAllOtherTextFields(false, currenttextfield, currenttextfield);
            }
            return false;
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HerstellingenSearchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HerstellingenSearchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HerstellingenSearchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HerstellingenSearchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HerstellingenSearchDialog dialog = new HerstellingenSearchDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseThisGUI;
    private javax.swing.JButton btnOpenHerstellingenDeleteDialog;
    private javax.swing.JButton btnOpenHerstellingenDetailsDialog;
    private javax.swing.JButton btnOpenHerstellingenEditDialog;
    private javax.swing.JButton btnSearchHerstellingen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBedragTot;
    private javax.swing.JLabel lblDefectnummer;
    private javax.swing.JLabel lblFietsnummer;
    private javax.swing.JLabel lblFoutmelding;
    private javax.swing.JLabel lblHerstellingId;
    private javax.swing.JLabel lblHuurderId;
    private javax.swing.JLabel lblKostprijs;
    private javax.swing.JLabel lblMeldingsdatum;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblZoekresultatenList;
    private javax.swing.JList lstZoekresultaten;
    private javax.swing.JTextField txtDefectnummer;
    private javax.swing.JTextField txtFietsnummer;
    private javax.swing.JTextField txtHerstellingId;
    private javax.swing.JTextField txtHuurderId;
    private javax.swing.JTextField txtKostprijsMax;
    private javax.swing.JTextField txtKostprijsMin;
    private javax.swing.JTextField txtMeldingsdatum;
    // End of variables declaration//GEN-END:variables
}
