/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fietsverhuur.swing;

import fietsverhuur.model.*;
import fietsverhuur.dao.*;
import java.util.ArrayList;
/**
 *
 * @author Myra
 */
public class HuurdersCreateDialog extends javax.swing.JDialog {

    /**
     * Creates new form VerhuringenCreateGUIb
     */
    private Resultaat formulierResultaat;

    public Resultaat getFormulierResultaat() {
        return formulierResultaat;
    }
    
    public enum Resultaat{
        GEANNULEERD,
        BEVESTIGD
    }
    
    public Huurder getHuurder() {
        String voornaam = txtVoornaam.getText();
        String achternaam = txtAchternaam.getText();
        String adres = txtAdres.getText();
        String stad = txtStad.getText();
        String telefoonnummer = txtTelefoonnummer.getText();
        String emailadres = txtEmailadres.getText();

        return new Huurder(voornaam, achternaam, adres, stad, telefoonnummer, emailadres);
    }
    
    public HuurdersCreateDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ArrayList<Huurder> lst = HuurderDao.getHuurders();
        int huurderId = 1 + lst.get(0).getHuurderId();
        txtHuurderId.setText(Integer.toString(huurderId));
    }
    public Resultaat showDialog() {
        this.setModal(true);
        this.setVisible(true);
        return this.formulierResultaat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmailadres = new javax.swing.JTextField();
        lblTelefoonnummer = new javax.swing.JLabel();
        txtTelefoonnummer = new javax.swing.JTextField();
        lblStad = new javax.swing.JLabel();
        lblEmailadres = new javax.swing.JLabel();
        btnCloseGUI = new javax.swing.JButton();
        btnSaveDataAndCloseGUI = new javax.swing.JButton();
        lblTitel = new javax.swing.JLabel();
        txtHuurderId = new javax.swing.JTextField();
        txtVoornaam = new javax.swing.JTextField();
        lblFoutmelding = new javax.swing.JLabel();
        lblVoornaam = new javax.swing.JLabel();
        txtAchternaam = new javax.swing.JTextField();
        lblAchternaam = new javax.swing.JLabel();
        lblHuurderId = new javax.swing.JLabel();
        txtAdres = new javax.swing.JTextField();
        lblAdres = new javax.swing.JLabel();
        txtStad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtEmailadres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailadresKeyReleased(evt);
            }
        });

        lblTelefoonnummer.setText("Telefoonnummer");

        txtTelefoonnummer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefoonnummerKeyReleased(evt);
            }
        });

        lblStad.setText("Stad*");

        lblEmailadres.setText("E-mailadres*");

        btnCloseGUI.setText("Annuleren");
        btnCloseGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseGUIActionPerformed(evt);
            }
        });

        btnSaveDataAndCloseGUI.setText("Maak huurder aan");
        btnSaveDataAndCloseGUI.setActionCommand("Maak huurder aan");
        btnSaveDataAndCloseGUI.setEnabled(false);
        btnSaveDataAndCloseGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDataAndCloseGUIActionPerformed(evt);
            }
        });

        lblTitel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTitel.setText("Nieuwe Huurder");

        txtHuurderId.setEnabled(false);

        txtVoornaam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVoornaamKeyReleased(evt);
            }
        });

        lblFoutmelding.setText(" ");

        lblVoornaam.setText("Voornaam*");

        txtAchternaam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAchternaamKeyReleased(evt);
            }
        });

        lblAchternaam.setText("Achternaam*");

        lblHuurderId.setText("HuurderId");

        txtAdres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdresKeyReleased(evt);
            }
        });

        lblAdres.setText("Adres*");
        lblAdres.setToolTipText("");

        txtStad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStadKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCloseGUI)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveDataAndCloseGUI))
                    .addComponent(txtAdres)
                    .addComponent(txtEmailadres)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTelefoonnummer)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtTelefoonnummer)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVoornaam, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVoornaam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAchternaam)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtAchternaam)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHuurderId)
                            .addComponent(txtHuurderId, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitel)
                            .addComponent(lblAdres)
                            .addComponent(lblEmailadres)
                            .addComponent(lblFoutmelding))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHuurderId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHuurderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVoornaam)
                    .addComponent(lblAchternaam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVoornaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAchternaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAdres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAdres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtTelefoonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStad)
                            .addComponent(lblTelefoonnummer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmailadres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmailadres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFoutmelding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCloseGUI)
                    .addComponent(btnSaveDataAndCloseGUI))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefoonnummerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoonnummerKeyReleased
        enableDisableOpslaanButton();
    }//GEN-LAST:event_txtTelefoonnummerKeyReleased

    private void txtVoornaamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVoornaamKeyReleased
        enableDisableOpslaanButton();
    }//GEN-LAST:event_txtVoornaamKeyReleased

    private void txtAchternaamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAchternaamKeyReleased
        enableDisableOpslaanButton();
    }//GEN-LAST:event_txtAchternaamKeyReleased

    private void txtAdresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdresKeyReleased
        enableDisableOpslaanButton();
    }//GEN-LAST:event_txtAdresKeyReleased

    private void txtStadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStadKeyReleased
        enableDisableOpslaanButton();
    }//GEN-LAST:event_txtStadKeyReleased

    private void txtEmailadresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailadresKeyReleased
        enableDisableOpslaanButton();
    }//GEN-LAST:event_txtEmailadresKeyReleased

    private void btnCloseGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseGUIActionPerformed
        this.formulierResultaat = Resultaat.GEANNULEERD;
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseGUIActionPerformed

    private void btnSaveDataAndCloseGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDataAndCloseGUIActionPerformed
        this.formulierResultaat = Resultaat.BEVESTIGD;
        this.setVisible(false);
    }//GEN-LAST:event_btnSaveDataAndCloseGUIActionPerformed

    public void enableDisableOpslaanButton() {
        if(txtVoornaam.getText().equals("") || txtAchternaam.getText().equals("") || txtAdres.getText().equals("")|| txtStad.getText().equals("") || txtEmailadres.getText().equals("")) {
            btnSaveDataAndCloseGUI.setEnabled(false);
            lblFoutmelding.setText("Vul a.u.b. alle velden in.");
            
        } else {
            if(CheckUserInput.isNameValid(txtVoornaam.getText(), lblFoutmelding)
                    && CheckUserInput.isNameValid(txtAchternaam.getText(), lblFoutmelding)
                    ) {
                btnSaveDataAndCloseGUI.setEnabled(true);
                lblFoutmelding.setText("");
            } else {
                btnSaveDataAndCloseGUI.setEnabled(false);
            }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HuurdersCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HuurdersCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HuurdersCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HuurdersCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HuurdersCreateDialog dialog = new HuurdersCreateDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseGUI;
    private javax.swing.JButton btnSaveDataAndCloseGUI;
    private javax.swing.JLabel lblAchternaam;
    private javax.swing.JLabel lblAdres;
    private javax.swing.JLabel lblEmailadres;
    private javax.swing.JLabel lblFoutmelding;
    private javax.swing.JLabel lblHuurderId;
    private javax.swing.JLabel lblStad;
    private javax.swing.JLabel lblTelefoonnummer;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblVoornaam;
    private javax.swing.JTextField txtAchternaam;
    private javax.swing.JTextField txtAdres;
    private javax.swing.JTextField txtEmailadres;
    private javax.swing.JTextField txtHuurderId;
    private javax.swing.JTextField txtStad;
    private javax.swing.JTextField txtTelefoonnummer;
    private javax.swing.JTextField txtVoornaam;
    // End of variables declaration//GEN-END:variables
}
