/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fietsverhuur.swing;


import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import fietsverhuur.model.*;
import fietsverhuur.dao.*;
import java.util.ArrayList;
/**
 *
 * @author Myra
 */
public class VerhuringenCreateDialog extends javax.swing.JDialog {

    /**
     * Creates new form VerhuringenCreateGUIb
     */
    private Resultaat formulierResultaat;

    public Resultaat getFormulierResultaat() {
        return formulierResultaat;
    }
    
    public enum Resultaat{
        GEANNULEERD,
        BEVESTIGD
    }
    
    public VerhuringenCreateDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ArrayList<Verhuring> lst = VerhuringDao.getVerhuringen();
        int verhuringId = 1 + lst.get(0).getVerhuringId();
        txtVerhuringId.setText(Integer.toString(verhuringId));
    }
    public Resultaat showDialog() {
        this.setModal(true);
        this.setVisible(true);
        return this.formulierResultaat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtKostprijs = new javax.swing.JTextField();
        lblFietsnummer = new javax.swing.JLabel();
        txtFietsnummer = new javax.swing.JTextField();
        lblHuurderId = new javax.swing.JLabel();
        lblKostprijs = new javax.swing.JLabel();
        btnCloseGUI = new javax.swing.JButton();
        btnSaveDataAndCloseGUI = new javax.swing.JButton();
        lblTitel = new javax.swing.JLabel();
        txtVerhuringId = new javax.swing.JTextField();
        txtBegindatum = new javax.swing.JTextField();
        lblFoutmelding = new javax.swing.JLabel();
        lblBegindatum = new javax.swing.JLabel();
        txtDuur = new javax.swing.JTextField();
        lblDuur = new javax.swing.JLabel();
        lblVerhuringId = new javax.swing.JLabel();
        txtEinddatum = new javax.swing.JTextField();
        lblEinddatum = new javax.swing.JLabel();
        txtHuurderId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtKostprijs.setEnabled(false);

        lblFietsnummer.setText("Fietsnummer *");

        txtFietsnummer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFietsnummerKeyReleased(evt);
            }
        });

        lblHuurderId.setText("HuurderId*");

        lblKostprijs.setText("Kostprijs");

        btnCloseGUI.setText("Annuleren");
        btnCloseGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseGUIActionPerformed(evt);
            }
        });

        btnSaveDataAndCloseGUI.setText("Maak verhuring aan");
        btnSaveDataAndCloseGUI.setEnabled(false);
        btnSaveDataAndCloseGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDataAndCloseGUIActionPerformed(evt);
            }
        });

        lblTitel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTitel.setText("Nieuwe Verhuring");

        txtVerhuringId.setEnabled(false);

        txtBegindatum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBegindatumKeyReleased(evt);
            }
        });

        lblFoutmelding.setText(" ");

        lblBegindatum.setText("Begindatum *");

        txtDuur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDuurKeyReleased(evt);
            }
        });

        lblDuur.setText("Duur (dagen) *");

        lblVerhuringId.setText("VerhuringId");

        txtEinddatum.setEnabled(false);

        lblEinddatum.setText("Einddatum");

        txtHuurderId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHuurderIdKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCloseGUI)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveDataAndCloseGUI))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBegindatum)
                            .addComponent(lblVerhuringId)
                            .addComponent(txtVerhuringId, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHuurderId, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFietsnummer)
                                    .addComponent(txtFietsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBegindatum, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHuurderId))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblKostprijs)
                                            .addComponent(txtKostprijs, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDuur, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDuur))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEinddatum)
                                            .addComponent(txtEinddatum)))))
                            .addComponent(lblFoutmelding))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVerhuringId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVerhuringId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBegindatum)
                                    .addComponent(lblDuur))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDuur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBegindatum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEinddatum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEinddatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHuurderId)
                            .addComponent(lblFietsnummer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHuurderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFietsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtKostprijs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKostprijs)
                        .addGap(26, 26, 26)))
                .addGap(18, 18, 18)
                .addComponent(lblFoutmelding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCloseGUI)
                    .addComponent(btnSaveDataAndCloseGUI))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFietsnummerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFietsnummerKeyReleased
        checkFields();
        enableDisableOpslaanButton();
    }//GEN-LAST:event_txtFietsnummerKeyReleased

    private void txtBegindatumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBegindatumKeyReleased
        checkFields();
        enableDisableOpslaanButton();
    }//GEN-LAST:event_txtBegindatumKeyReleased

    private void txtDuurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuurKeyReleased
        checkFields();
        enableDisableOpslaanButton();
    }//GEN-LAST:event_txtDuurKeyReleased

    private void txtHuurderIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHuurderIdKeyReleased
        checkFields();
        enableDisableOpslaanButton();
    }//GEN-LAST:event_txtHuurderIdKeyReleased

    private void btnCloseGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseGUIActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseGUIActionPerformed

    private void btnSaveDataAndCloseGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDataAndCloseGUIActionPerformed
        this.setVisible(false);
 
        Date begindatum = CheckUserInput.parseDate(txtBegindatum.getText());
        int duurInDagen = Integer.parseInt(txtDuur.getText());
        int huurderId = Integer.parseInt(txtHuurderId.getText());
        int fietsnummer = Integer.parseInt(txtFietsnummer.getText());
        
        Verhuring nieuweVerhuring = new Verhuring(begindatum, duurInDagen, huurderId, fietsnummer);
        VerhuringDao.voegVerhuringToe(nieuweVerhuring);
    }//GEN-LAST:event_btnSaveDataAndCloseGUIActionPerformed

    public void enableDisableOpslaanButton() {
        if(txtBegindatum.getText().equals("") || txtDuur.getText().equals("") || txtHuurderId.getText().equals("") || txtFietsnummer.getText().equals("")) {
            btnSaveDataAndCloseGUI.setEnabled(false);
            lblFoutmelding.setText("Vul a.u.b. alle velden in.");
            
        } else {
            if(CheckUserInput.doesFietsnummerExist(txtFietsnummer.getText(), lblFoutmelding)
                    && CheckUserInput.doesHuurderIdExist(txtHuurderId.getText(), lblFoutmelding)
                    && CheckUserInput.isDateParsable(txtBegindatum.getText(), lblFoutmelding)
                    && CheckUserInput.isDuurValid(txtDuur.getText(), lblFoutmelding)
                    ) {
                btnSaveDataAndCloseGUI.setEnabled(true);
                lblFoutmelding.setText("");
            } else {
                btnSaveDataAndCloseGUI.setEnabled(false);
            }
        }
    }
    public void checkFields() {
        if(CheckUserInput.isDateParsable(txtBegindatum.getText(), lblFoutmelding) && CheckUserInput.isDuurValid(txtDuur.getText(), lblFoutmelding)) {
            txtEinddatum.setText(Calculate.calculateEinddatum(txtBegindatum.getText(), Integer.parseInt(txtDuur.getText())));
        } else {
            txtEinddatum.setText("");
        }
        
        if(CheckUserInput.isDuurValid(txtDuur.getText(), lblFoutmelding)&& CheckUserInput.isStringInteger(txtFietsnummer.getText())) {
            double kostprijs = Calculate.calculateVerhuringKostprijs(Integer.parseInt(txtDuur.getText()), Integer.parseInt(txtFietsnummer.getText()));
            txtKostprijs.setText("€" + Calculate.roundAndAddZeroes(kostprijs, 2));
        }
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerhuringenCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerhuringenCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerhuringenCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerhuringenCreateDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerhuringenCreateDialog dialog = new VerhuringenCreateDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseGUI;
    private javax.swing.JButton btnSaveDataAndCloseGUI;
    private javax.swing.JLabel lblBegindatum;
    private javax.swing.JLabel lblDuur;
    private javax.swing.JLabel lblEinddatum;
    private javax.swing.JLabel lblFietsnummer;
    private javax.swing.JLabel lblFoutmelding;
    private javax.swing.JLabel lblHuurderId;
    private javax.swing.JLabel lblKostprijs;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblVerhuringId;
    private javax.swing.JTextField txtBegindatum;
    private javax.swing.JTextField txtDuur;
    private javax.swing.JTextField txtEinddatum;
    private javax.swing.JTextField txtFietsnummer;
    private javax.swing.JTextField txtHuurderId;
    private javax.swing.JTextField txtKostprijs;
    private javax.swing.JTextField txtVerhuringId;
    // End of variables declaration//GEN-END:variables
}
