/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fietsverhuur.swing;

import fietsverhuur.dao.*;
import fietsverhuur.model.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Myra
 */
public class VerhuringenSearchDialog extends javax.swing.JDialog {

    private DefaultListModel<Verhuring> verhuringenModel;
    
    public VerhuringenSearchDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        verhuringenModel = new DefaultListModel<Verhuring>();
        lstZoekresultaten.setModel(verhuringenModel);
    }
    
    public void showDialog() {
        this.setModal(true);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCloseThisGUI = new javax.swing.JButton();
        lblVerhuringId = new javax.swing.JLabel();
        txtHuurderId = new javax.swing.JTextField();
        lblDuurTot = new javax.swing.JLabel();
        txtDuurMax = new javax.swing.JTextField();
        lblBedragTot = new javax.swing.JLabel();
        txtKostprijsMax = new javax.swing.JTextField();
        lblZoekresultatenList = new javax.swing.JLabel();
        btnSearchVerhuringen = new javax.swing.JButton();
        lblTitel = new javax.swing.JLabel();
        btnOpenVerhuringenEditDialog = new javax.swing.JButton();
        btnOpenVerhuringenDeleteDialog = new javax.swing.JButton();
        txtVerhuringId = new javax.swing.JTextField();
        lblKostprijs = new javax.swing.JLabel();
        lblBegindatum = new javax.swing.JLabel();
        txtKostprijsMin = new javax.swing.JTextField();
        txtBegindatum = new javax.swing.JTextField();
        lblDuur = new javax.swing.JLabel();
        txtDuurMin = new javax.swing.JTextField();
        lblEinddatum = new javax.swing.JLabel();
        txtEinddatum = new javax.swing.JTextField();
        lblFietsnummer = new javax.swing.JLabel();
        txtFietsnummer = new javax.swing.JTextField();
        lblHuurderId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstZoekresultaten = new javax.swing.JList();
        lblFoutmelding = new javax.swing.JLabel();
        btnOpenVerhuringenDetailsDialog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCloseThisGUI.setText("Sluit venster");
        btnCloseThisGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseThisGUIActionPerformed(evt);
            }
        });

        lblVerhuringId.setText("VerhuringId");

        txtHuurderId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHuurderIdKeyReleased(evt);
            }
        });

        lblDuurTot.setText("tot");

        txtDuurMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDuurMaxKeyReleased(evt);
            }
        });

        lblBedragTot.setText("tot");

        txtKostprijsMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKostprijsMaxKeyReleased(evt);
            }
        });

        lblZoekresultatenList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblZoekresultatenList.setText("Resultaten:");

        btnSearchVerhuringen.setText("Zoek verhuring");
        btnSearchVerhuringen.setEnabled(false);
        btnSearchVerhuringen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchVerhuringenActionPerformed(evt);
            }
        });

        lblTitel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTitel.setText("Zoek verhuringen");
        lblTitel.setToolTipText("");

        btnOpenVerhuringenEditDialog.setText("Details/Edit selectie");
        btnOpenVerhuringenEditDialog.setEnabled(false);
        btnOpenVerhuringenEditDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenVerhuringenEditDialogActionPerformed(evt);
            }
        });

        btnOpenVerhuringenDeleteDialog.setText("Verwijder selectie");
        btnOpenVerhuringenDeleteDialog.setEnabled(false);
        btnOpenVerhuringenDeleteDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenVerhuringenDeleteDialogActionPerformed(evt);
            }
        });

        txtVerhuringId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVerhuringIdKeyReleased(evt);
            }
        });

        lblKostprijs.setText("Kostprijs (€)");

        lblBegindatum.setText("Begindatum");

        txtKostprijsMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKostprijsMinKeyReleased(evt);
            }
        });

        txtBegindatum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBegindatumKeyReleased(evt);
            }
        });

        lblDuur.setText("Duur (dagen)");

        txtDuurMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDuurMinKeyReleased(evt);
            }
        });

        lblEinddatum.setText("Einddatum");

        txtEinddatum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEinddatumKeyReleased(evt);
            }
        });

        lblFietsnummer.setText("Fietsnummer");

        txtFietsnummer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFietsnummerKeyReleased(evt);
            }
        });

        lblHuurderId.setText("HuurderId");

        lstZoekresultaten.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstZoekresultatenValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstZoekresultaten);

        lblFoutmelding.setText(" ");

        btnOpenVerhuringenDetailsDialog.setText("Details selectie");
        btnOpenVerhuringenDetailsDialog.setEnabled(false);
        btnOpenVerhuringenDetailsDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenVerhuringenDetailsDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOpenVerhuringenDeleteDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenVerhuringenEditDialog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOpenVerhuringenDetailsDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCloseThisGUI)
                            .addComponent(lblZoekresultatenList)
                            .addComponent(lblTitel)
                            .addComponent(btnSearchVerhuringen)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVerhuringId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVerhuringId))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBegindatum, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBegindatum))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDuurMin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblDuurTot)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDuurMax, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblDuur))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEinddatum)
                                    .addComponent(txtEinddatum, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblHuurderId)
                                    .addComponent(txtHuurderId, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFietsnummer)
                                    .addComponent(txtFietsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKostprijs)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtKostprijsMin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblBedragTot)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtKostprijsMax, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblFoutmelding))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVerhuringId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBegindatum, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDuur)
                        .addComponent(lblEinddatum)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBegindatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtVerhuringId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDuurMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDuurTot)
                        .addComponent(txtDuurMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEinddatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHuurderId)
                            .addComponent(lblFietsnummer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHuurderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFietsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblKostprijs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKostprijsMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBedragTot)
                            .addComponent(txtKostprijsMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnSearchVerhuringen)
                .addGap(18, 18, 18)
                .addComponent(lblFoutmelding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblZoekresultatenList, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpenVerhuringenEditDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpenVerhuringenDeleteDialog)
                        .addGap(11, 11, 11)
                        .addComponent(btnOpenVerhuringenDetailsDialog)))
                .addGap(18, 18, 18)
                .addComponent(btnCloseThisGUI)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHuurderIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHuurderIdKeyReleased
        if(checkIfEmpty(txtHuurderId)) {
            btnSearchVerhuringen.setEnabled(false);
        } else {
            if(CheckUserInput.doesHuurderIdExist(txtHuurderId.getText(), lblFoutmelding)) {
                btnSearchVerhuringen.setEnabled(true);
            } else {
                btnSearchVerhuringen.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtHuurderIdKeyReleased

    private void txtDuurMaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuurMaxKeyReleased
         if(checkIfEmpty(txtDuurMax)) {
             btnSearchVerhuringen.setEnabled(false);
         } else {
             if(CheckUserInput.isDuurValid(txtDuurMax.getText(), lblFoutmelding)) {
                 btnSearchVerhuringen.setEnabled(true);
             } else {
                 btnSearchVerhuringen.setEnabled(false);
             }
         }
    }//GEN-LAST:event_txtDuurMaxKeyReleased

    private void txtKostprijsMaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKostprijsMaxKeyReleased
         if(checkIfEmpty(txtKostprijsMax)) {
            btnSearchVerhuringen.setEnabled(false);
        } else {
            if(CheckUserInput.isStringDouble(txtKostprijsMax.getText())) {
                btnSearchVerhuringen.setEnabled(true);
                lblFoutmelding.setText("");
            } else {
                btnSearchVerhuringen.setEnabled(false);
                lblFoutmelding.setText("Vul a.u.b. een geldig bedrag in.");
            }
        }
    }//GEN-LAST:event_txtKostprijsMaxKeyReleased

    private void txtVerhuringIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVerhuringIdKeyReleased
        if(checkIfEmpty(txtVerhuringId)) {
            btnSearchVerhuringen.setEnabled(false);
        } else {
            if(CheckUserInput.isStringInteger(txtVerhuringId.getText())) {
                btnSearchVerhuringen.setEnabled(true);
                lblFoutmelding.setText("");
            } else {
                btnSearchVerhuringen.setEnabled(false);
                lblFoutmelding.setText("Vul a.u.b. een geldig nummer in.");
            }
        }
    }//GEN-LAST:event_txtVerhuringIdKeyReleased

    private void txtKostprijsMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKostprijsMinKeyReleased
        if(checkIfEmpty(txtKostprijsMin)) {
            btnSearchVerhuringen.setEnabled(false);
        } else {
            if(CheckUserInput.isStringDouble(txtKostprijsMin.getText())) {
                btnSearchVerhuringen.setEnabled(true);
                lblFoutmelding.setText("");
            } else {
                btnSearchVerhuringen.setEnabled(false);
                lblFoutmelding.setText("Vul a.u.b. een geldig bedrag in.");
            }
        }
    }//GEN-LAST:event_txtKostprijsMinKeyReleased

    private void txtBegindatumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBegindatumKeyReleased
        if(checkIfEmpty(txtBegindatum)) {
            btnSearchVerhuringen.setEnabled(false);
        } else {
            if(CheckUserInput.isDateParsable(txtBegindatum.getText(), lblFoutmelding)) {
                btnSearchVerhuringen.setEnabled(true);
            } else {
                btnSearchVerhuringen.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtBegindatumKeyReleased

    private void txtDuurMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuurMinKeyReleased
        if(checkIfEmpty(txtDuurMin)) {
            btnSearchVerhuringen.setEnabled(false);
        } else {
             if(CheckUserInput.isDuurValid(txtDuurMin.getText(), lblFoutmelding)) {
                 btnSearchVerhuringen.setEnabled(true);
             } else {
                 btnSearchVerhuringen.setEnabled(false);
             }
         }
    }//GEN-LAST:event_txtDuurMinKeyReleased

    private void txtEinddatumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEinddatumKeyReleased
        if(checkIfEmpty(txtEinddatum)) {
            btnSearchVerhuringen.setEnabled(false);
        } else {
            if(CheckUserInput.isDateParsable(txtEinddatum.getText(), lblFoutmelding)) {
                btnSearchVerhuringen.setEnabled(true);
            } else {
                btnSearchVerhuringen.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtEinddatumKeyReleased

    private void txtFietsnummerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFietsnummerKeyReleased
        if(checkIfEmpty(txtFietsnummer)) {
            btnSearchVerhuringen.setEnabled(false);
        } else {
            if(CheckUserInput.doesFietsnummerExist(txtFietsnummer.getText(), lblFoutmelding)) {
                btnSearchVerhuringen.setEnabled(true);
            } else {
                btnSearchVerhuringen.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtFietsnummerKeyReleased

    private void btnCloseThisGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseThisGUIActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseThisGUIActionPerformed

    private void btnOpenVerhuringenEditDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenVerhuringenEditDialogActionPerformed
        ArrayList <Verhuring> verhuringenToEdit = new ArrayList <Verhuring> (lstZoekresultaten.getSelectedValuesList());
        JFrame frame= (JFrame) SwingUtilities.getWindowAncestor(this);
        VerhuringenEditDialog dialog = new VerhuringenEditDialog(frame, true);
        dialog.createTextFieldsAndSetVerhuringen(verhuringenToEdit);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        btnSearchVerhuringenActionPerformed(evt);
    }//GEN-LAST:event_btnOpenVerhuringenEditDialogActionPerformed

    private void btnOpenVerhuringenDeleteDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenVerhuringenDeleteDialogActionPerformed
        ArrayList <Verhuring> verhuringenToDelete = new ArrayList <Verhuring> (lstZoekresultaten.getSelectedValuesList());
        JFrame frame= (JFrame) SwingUtilities.getWindowAncestor(this);
        VerhuringenDeleteDialog dialog = new VerhuringenDeleteDialog(frame, true);
        dialog.createTextFieldsAndSetVerhuringen(verhuringenToDelete);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
        btnSearchVerhuringenActionPerformed(evt);
    }//GEN-LAST:event_btnOpenVerhuringenDeleteDialogActionPerformed

    private void btnSearchVerhuringenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchVerhuringenActionPerformed
        verhuringenModel.clear();
        if(txtVerhuringId.isEnabled()) {
            int verhuringid = Integer.parseInt(txtVerhuringId.getText());
            Verhuring gevondenVerhuring = VerhuringDao.getVerhuringById(verhuringid);
            verhuringenModel.addElement(gevondenVerhuring);
        }
        if(txtBegindatum.isEnabled()) {
            try {
                Date begindatum = Calculate.df.parse(txtBegindatum.getText());
                ArrayList<Verhuring> gevondenVerhuringenLijst = VerhuringDao.getVerhuringenByBegindatum(begindatum);
                for(Verhuring gevondenVerhuring : gevondenVerhuringenLijst) {
                    verhuringenModel.addElement(gevondenVerhuring);
                }
                
            } catch (ParseException ex) {
                lblFoutmelding.setText("Gelieve een geldige datum in te voeren.");
            }
        }
        if(txtDuurMin.isEnabled()) {
            int duurMin = 0;
            int duurMax = 366;
            if(!txtDuurMin.getText().equals("")) {
                duurMin = Integer.parseInt(txtDuurMin.getText());
            }
            if(!txtDuurMax.getText().equals("")) {
                duurMax = Integer.parseInt(txtDuurMax.getText());
            }
            ArrayList<Verhuring> gevondenVerhuringenLijst = VerhuringDao.getVerhuringenByDuurInDagen(duurMin, duurMax);
            for(Verhuring gevondenVerhuring : gevondenVerhuringenLijst) {
                verhuringenModel.addElement(gevondenVerhuring);
            }
        }
        if(txtEinddatum.isEnabled()) {
            try {
                Date einddatum = Calculate.df.parse(txtEinddatum.getText());
                ArrayList<Verhuring> gevondenVerhuringenLijst = VerhuringDao.getVerhuringenByEinddatum(einddatum);
                for(Verhuring gevondenVerhuring : gevondenVerhuringenLijst) {
                    verhuringenModel.addElement(gevondenVerhuring);
                }
                
            } catch (ParseException ex) {
                lblFoutmelding.setText("Gelieve een geldige datum in te voeren.");
            }
        }
        if(txtHuurderId.isEnabled()) {
            int huurderId = Integer.parseInt(txtHuurderId.getText());
            ArrayList<Verhuring> gevondenVerhuringenLijst = VerhuringDao.getVerhuringenByHuurderId(huurderId);
            for(Verhuring gevondenVerhuring : gevondenVerhuringenLijst) {
                verhuringenModel.addElement(gevondenVerhuring);
            }
        }
        if(txtFietsnummer.isEnabled()) {
            int fietsnummer = Integer.parseInt(txtFietsnummer.getText());
            ArrayList<Verhuring> gevondenVerhuringenLijst = VerhuringDao.getVerhuringenByFietsnummer(fietsnummer);
            for(Verhuring gevondenVerhuring : gevondenVerhuringenLijst) {
                verhuringenModel.addElement(gevondenVerhuring);
            }
        }
        if(txtKostprijsMin.isEnabled()) {
            double kostprijsMin = 0;
            double kostprijsMax = 99999;
            if(!txtKostprijsMin.getText().equals("")) {
                kostprijsMin = Integer.parseInt(txtKostprijsMin.getText());
            }
            if(!txtKostprijsMax.getText().equals("")) {
                kostprijsMax = Integer.parseInt(txtKostprijsMax.getText());
            }
            ArrayList<KostprijsPerVerhuringId> gevondenKostprijsPerVerhuringIdLijst = KostprijsPerVerhuringIdDao.getKostprijzenPerVerhuringIdByKostprijs(kostprijsMin, kostprijsMax);
            for(KostprijsPerVerhuringId gevondenKostprijsPerVerhuringId : gevondenKostprijsPerVerhuringIdLijst) {
                Verhuring gevondenVerhuring = VerhuringDao.getVerhuringById(gevondenKostprijsPerVerhuringId.getVerhuringId());
                verhuringenModel.addElement(gevondenVerhuring);
            }
        }
    }//GEN-LAST:event_btnSearchVerhuringenActionPerformed

    private void lstZoekresultatenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstZoekresultatenValueChanged
        if (lstZoekresultaten.isSelectionEmpty()) {
            btnOpenVerhuringenDeleteDialog.setEnabled(false);
            btnOpenVerhuringenEditDialog.setEnabled(false);
            btnOpenVerhuringenDetailsDialog.setEnabled(false);
        } else {
            btnOpenVerhuringenDeleteDialog.setEnabled(true);
            btnOpenVerhuringenEditDialog.setEnabled(true);
            btnOpenVerhuringenDetailsDialog.setEnabled(true);
        }
    }//GEN-LAST:event_lstZoekresultatenValueChanged

    private void btnOpenVerhuringenDetailsDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenVerhuringenDetailsDialogActionPerformed
        ArrayList <Verhuring> verhuringenToShow = new ArrayList <Verhuring> (lstZoekresultaten.getSelectedValuesList());
        JFrame frame= (JFrame) SwingUtilities.getWindowAncestor(this);
        VerhuringenDetailsDialog dialog = new VerhuringenDetailsDialog(frame, true);
        dialog.createTextFieldsAndSetVerhuringen(verhuringenToShow);
        dialog.setLocation(this.getX() + this.getWidth()/2, this.getY() + this.getHeight()/2);
        dialog.showDialog();
    }//GEN-LAST:event_btnOpenVerhuringenDetailsDialogActionPerformed

    public void setAllOtherTextFields(boolean status, javax.swing.JTextField textfield1, javax.swing.JTextField textfield2) {
        ArrayList <javax.swing.JTextField> textfields = new ArrayList<>(9);
        textfields.add(txtVerhuringId);
        textfields.add(txtBegindatum);
        textfields.add(txtDuurMin);
        textfields.add(txtDuurMax);
        textfields.add(txtEinddatum);
        textfields.add(txtHuurderId);
        textfields.add(txtFietsnummer);
        textfields.add(txtKostprijsMin);
        textfields.add(txtKostprijsMax);
        for(javax.swing.JTextField currenttextfield : textfields) {
            if(currenttextfield != textfield1 && currenttextfield != textfield2) {
                currenttextfield.setEnabled(status);
            }
        }
    }
    public boolean checkIfEmpty(javax.swing.JTextField currenttextfield) {
        boolean hasTwinTextfield = false;
        boolean noTextInTwintextfield = true;
        javax.swing.JTextField twintextfield = null;
        
        if(currenttextfield == txtKostprijsMin) {twintextfield = txtKostprijsMax; hasTwinTextfield = true;}
        if(currenttextfield == txtKostprijsMax) {twintextfield = txtKostprijsMin; hasTwinTextfield = true;}
        if(currenttextfield == txtDuurMin) {twintextfield = txtDuurMax; hasTwinTextfield = true;}
        if(currenttextfield == txtDuurMax) {twintextfield = txtDuurMin; hasTwinTextfield = true;}
        
        if(hasTwinTextfield) {
            if(!twintextfield.getText().equals("")) {
                noTextInTwintextfield = false;
            }
        }
        
        if(currenttextfield.getText().equals("") && noTextInTwintextfield) {
            setAllOtherTextFields(true, currenttextfield, currenttextfield);
            lblFoutmelding.setText("");
            return true;
        } else {
            if(hasTwinTextfield) {
                setAllOtherTextFields(false, currenttextfield, twintextfield);
            } else {
                setAllOtherTextFields(false, currenttextfield, currenttextfield);
            }
            return false;
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerhuringenSearchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerhuringenSearchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerhuringenSearchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerhuringenSearchDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerhuringenSearchDialog dialog = new VerhuringenSearchDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseThisGUI;
    private javax.swing.JButton btnOpenVerhuringenDeleteDialog;
    private javax.swing.JButton btnOpenVerhuringenDetailsDialog;
    private javax.swing.JButton btnOpenVerhuringenEditDialog;
    private javax.swing.JButton btnSearchVerhuringen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBedragTot;
    private javax.swing.JLabel lblBegindatum;
    private javax.swing.JLabel lblDuur;
    private javax.swing.JLabel lblDuurTot;
    private javax.swing.JLabel lblEinddatum;
    private javax.swing.JLabel lblFietsnummer;
    private javax.swing.JLabel lblFoutmelding;
    private javax.swing.JLabel lblHuurderId;
    private javax.swing.JLabel lblKostprijs;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblVerhuringId;
    private javax.swing.JLabel lblZoekresultatenList;
    private javax.swing.JList lstZoekresultaten;
    private javax.swing.JTextField txtBegindatum;
    private javax.swing.JTextField txtDuurMax;
    private javax.swing.JTextField txtDuurMin;
    private javax.swing.JTextField txtEinddatum;
    private javax.swing.JTextField txtFietsnummer;
    private javax.swing.JTextField txtHuurderId;
    private javax.swing.JTextField txtKostprijsMax;
    private javax.swing.JTextField txtKostprijsMin;
    private javax.swing.JTextField txtVerhuringId;
    // End of variables declaration//GEN-END:variables
}
